### PR TITLE
ENH: Creating default topic on creating message broker

### LINKED ISSUE #4216: As User - I want a new Message Broker to have a Default Topic already set up for me
**Overview:**
Similar to Services we want a new Message Broker to include an automatically generated default topic as we expect it will help developers to understand how to use it and save some steps which the developer will always do if he wants to use a Message Broker.

**Design Example:**

Image

**Requirements:**

- [ ] When a new Message Broker is created add an auto-generated topic
    - [ ] Topic Display Name - "Topic 1"
    - [ ] Topic Name - "topic.1"
    - [ ] Topic Description - "An automatically created topic to be used with the Message Broker"

### PR DESCRIPTION
**Pull request by Ahtritus**
Close #4216 

## PR Details

Creating a default topic on creating a message broker

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by Ahtritus** [comment]
@GreenMachine01 Kind of think there must be a better way of achieving this. Also, seems like after the default topic is created, another gql request is made which throws a 400 error, not able to figure that part out.

**Comment by abrl91** [comment]
run branch

**Comment by abrl91** [comment]
@Ahtritus you have a compilation error on this file `TopicForm.tsx`
image

You have to add this import 
```ts
import { DisplayNameField } from "../Components/DisplayNameField";
```

**Comment by Ahtritus** [comment]
There were some merge conflicts which caused this, my fork was not up to date with the master here. However, I'm still wondering why was the `TextInputField` changed to `DisplayNameField`? Anyway, I've resolved the conflicts and am pushing it.

**Comment by abrl91** [comment]
Hey @Ahtritus 
I ran your branch locally. Well done! I saw the auto-generated topic on the topics page of the generated broker and the enum of this topic was generated in the app.

However, I noticed two issues:
1. The new message broker with its newly created topic is not added to the pending changes:
image
For example, have a look at the pending changes after I added `my-topic.v1`
image

2. @arielweinberger @GreenMachine01 please review the name of the auto-generated topic (Topic1), I think we should auto-generate a different topic name.

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]
I expected to see the new behavior on the server side and not on the client side. 
see this line of code for default entities - it should be the same for topics 
https://github.com/amplication/amplication/blob/ed80357733cc315eaa7a8da92f6d7f6313f9bce2/packages/amplication-server/src/core/resource/resource.service.ts#L185

but, please note that the topic should only be added for MessageBroker - so your code should be in this function 
https://github.com/amplication/amplication/blob/ed80357733cc315eaa7a8da92f6d7f6313f9bce2/packages/amplication-server/src/core/resource/resource.service.ts#L155

**Comment by yuval-hazaz** [comment]
> Hey @Ahtritus I ran your branch locally. Well done! I saw the auto-generated topic on the topics page of the generated broker and the enum of this topic was generated in the app.
> 
> However, I noticed two issues:
> 
> 1. The new message broker with its newly created topic is not added to the pending changes:
>    image
>    For example, have a look at the pending changes after I added `my-topic.v1`
>    image
> 2. @arielweinberger @GreenMachine01 please review the name of the auto-generated topic (Topic1), I think we should auto-generate a different topic name.
> 
> Please, fix issue number 1 and regarding the second issue, let's wait for Ariel and Erez.

@abrl91 please see my comments about doing the change on the server side. 
the original issue was created because we wanted to see a pending change for the new message broker when it is created, so there is no sense to add the topic only when the user enters the Topics page. 
also, in any case, it does not make sense to do this change on the client side regardless of the original reason.

**Comment by abrl91** [comment]
@Ahtritus can you make these changes?

**Comment by Ahtritus** [comment]
> Member

I'm looking into it but am yet to successfully do it

**Comment by Ahtritus** [comment]
> I expected to see the new behavior on the server side and not on the client side. see this line of code for default entities - it should be the same for topics
> 
> https://github.com/amplication/amplication/blob/ed80357733cc315eaa7a8da92f6d7f6313f9bce2/packages/amplication-server/src/core/resource/resource.service.ts#L185
> 
> but, please note that the topic should only be added for MessageBroker - so your code should be in this function
> 
> https://github.com/amplication/amplication/blob/ed80357733cc315eaa7a8da92f6d7f6313f9bce2/packages/amplication-server/src/core/resource/resource.service.ts#L155

I'm calling the `create` method from serviceTopicsService after the messageBroker resource has been created. However it doesn't seem to work. Any pointers where I should look?

**Comment by abrl91** [comment]
@Ahtritus I want to update you that we didn't forget you :)
We will answer your questions and review your PR probably next week.

**Comment by tupe12334** [comment]
@Ahtritus any updates? do you want to still work on that?

**Comment by Ahtritus** [comment]
> @Ahtritus any updates? do you want to still work on that?

Hey, sorry for the late reply. I'm a bit busy with personal work and won't be able to focus on this before next month. If that is acceptable, then I would like to continue being assigned to this and I can push the new changes in a week or so. If not, you can assign it to someone else.

**Comment by yuval-hazaz** [comment]
@Ahtritus, thanks for your contribution and for supporting the project! 
I will close this PR for now. Please feel free to pick any issue that is available for the community when ever you are ready

**Pull request closed without merging**
