### PR TITLE
chore: fix ci affected to work on next to master PR

### PR DESCRIPTION
**Pull request by overbit**
Close: #4429 

## PR Details

Update ci affected workflow to only be triggered on actions against a pull request. 
This will fix the scenario where CI workflow triggered by push on `next` branch will end not running any build due to Nx not detecting any changes that will affect projects due to the comparison of the HEAD of the `next` branch against itself.

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by overbit** [comment]
There is an issue with one of the action we use.
⚠️  This PR is blocked until the `nx-set-shas` action gets fixed:  https://github.com/nrwl/nx-set-shas/pull/80

**Comment by arielweinberger** [comment]
Is it worth using a fork in the meantime?

**Comment by overbit** [comment]
Actually, I might be wrong. Since the `pull_request_target` runs in the context of the base of the pull request meaning we would not get the latest changes of a PR. We should use the `pull_request` event in this case

**Comment by arielweinberger** [comment]
The downside is that pull_request does not allot non-maintainers to get access to secrets (even if we manually approve the runs). So any PR from maintainers won't be able to successfully run CI.

**Comment by overbit** [comment]
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Review by arielweinberger — APPROVED** [review]

**Pull request merged**
