### PR TITLE
[Fix - 2239]: Missing Commit/Rebuild Collapse button

### PR DESCRIPTION
**Pull request by muhsinkamil**
Issue Number: https://github.com/amplication/amplication/issues/2239

## PR Details

- Add collapse button on pending changes panel

## PR Checklist
- [x] `npm test` doesn't throw any error

### CODE REVIEW

**Comment by mshidlov** [comment]
@muhsinkamil thank you for submitting this PR I'm going to review it soon

**Comment by mshidlov** [comment]
@muhsinkamil I solved a conflict on the PR,  It looks ok I'm doing checks right now

**Comment by muhsinkamil** [comment]
@mshidlov Was there a conflict ? Might be due to today's merges. Sorry about that.

**Comment by mshidlov** [comment]
@muhsinkamil its ok if you would like you can validate that I didn't break your changes

**Review by mshidlov — APPROVED** [review]

**Comment by mshidlov** [comment]
@yuval-hazaz this looks ok please review as well (deployed to staging)

**Pull request merged**
