### PR TITLE
bugfix: Imported lodash as a single library(dsg)

### PR DESCRIPTION
**Pull request by ShreyaPrasad1209**
Issue Number: #2736 

## PR Details

- Instead of importing each lodash function separately, I have imported the whole lodash library. In files where lodash is being used, I've imported specific modules from the whole lodash library itself instead of importing specific lodash functions. 
- I have not added any additional tests as asked in PR checklist below because there's no change in functionality of the code.

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by souravjain540** [comment]
Thanks for the PR @ShreyaPrasad1209 

@tupe12334 please review this on priority!

**Review by yuval-hazaz — APPROVED** [review]
thanks for your first contribution with Amplcation
well done

**Comment by yuval-hazaz** [comment]
@ShreyaPrasad1209 please have a look at the errors on the actions
image

**Comment by tupe12334** [comment]
@ShreyaPrasad1209 Are you still on that?

**Pull request merged**
