### PR TITLE
Fix Bug #3652  Changing SERVER_PORT variable to PORT

### PR DESCRIPTION
**Pull request by ahlavorato**
Issue Number: [#3652](https://github.com/amplication/amplication/issues/3652)

## PR Details
This Pull request fix the bug of the environment variable used being the wrong name. 
Right now is impossible to change the value of the port inside of .env value and it will reflefected in the main.ts file

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by abrl91 — APPROVED** [review]

**Comment by abrl91** [comment]
run branch

**Review by abrl91 — COMMENTED** [review]
I approved, but I see that there are changes on `package-lock.json` that I don't understand how and why it happened, for example:
image

Do you have any clue why it happened? did you run npm install/ bootstrap?

**Review by abrl91 — CHANGES_REQUESTED** [review]
Can you undo the changes on the `package-lock.json` file?

**Comment by ahlavorato** [comment]
> I approved, but I see that there are changes on `package-lock.json` that I don't understand how and why it happened, for example: image
> 
> Do you know why it happened? did you run npm install/ bootstrap?

I run npm and boostrap command, but I already undo it

**Review by abrl91 — APPROVED** [review]

**Pull request merged**
