### PR TITLE
chore: release v1.4.3

### PR DESCRIPTION
**Pull request by overbit**
## PR Details

Release v1.4.3
 
## Manual steps

⚠️ We need to run the data migration script: `packages/amplication-server/migration-scripts/git-organization-provider-properties.ts` [quote @abrl91](https://github.com/amplication/amplication/pull/5522#issuecomment-1479923488)

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by abrl91** [comment]
run the data migration script `packages/amplication-server/migration-scripts/git-organization-provider-properties.ts`

**Comment by overbit** [comment]
@all-contributors please add @overbit

**Comment by overbit** [comment]
@all-contributors please add @overbit for code

**Comment by abrl91** [comment]
we need to run the data migration script: `packages/amplication-server/migration-scripts/git-organization-provider-properties.ts`

**Pull request merged**
