### PR TITLE
feat(cli): Initial architecture with login and create commands

### PR DESCRIPTION
**Pull request by noctifer20**
CLI implementation with:
- [oclif](https://github.com/oclif/oclif) as bootstraper
- [apollo-boost](https://www.npmjs.com/package/apollo-boost) along with [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) as apollo client
- [cli-ux](https://github.com/oclif/cli-ux) as IO utility

### CODE REVIEW

**Comment by noctifer20** [comment]
Upon executing `amp-oc login` and entering `email` and `password`, auth token is being fetched and stored in [config directory](https://oclif.io/docs/config)

**Comment by yuval-hazaz** [comment]
@noctifer20 that looks great! I will pull this branch to explore and learn the design and tools you used.
This should definitely get into our roadmap, with continuous support for ongoing new features and APIs

**Comment by noctifer20** [comment]
I wrapped commands with [`ConfiguredCommand`](https://github.com/noctifer20/amplication/blob/cli-draft/packages/amplication-cli/src/configured-command.ts#L12) class, mainly for 2 reasons:

- [oclif hooks](https://oclif.io/docs/hooks) are missing command context, so if a command is to make changes in the config, there is no way (AFAIK) of passing those changes to `oclif's postrun hook`
- 2nd reason is to fetch and parse config on every command run, and functionality to restrict access based on config

**Comment by yuval-hazaz** [comment]
@all-contributors please add @noctifer20  for code

**Pull request merged**
