### PR TITLE
docs (Readme): Convert logo to clickable Link

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
Close https://github.com/amplication/amplication/issues/4210

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by kailashchoudhary11** [comment]
@yuval-hazaz Please Review!

**Comment by souravjain540** [comment]
please open an issue first related to this.

**Comment by kailashchoudhary11** [comment]
> please open an issue first related to this.

Done!

**Comment by kailashchoudhary11** [comment]
Resolves #1240

**Review by souravjain540 — APPROVED** [review]

**Pull request merged**
