### PR TITLE
Feat(DSG): auto-gen message

### PR DESCRIPTION
**Pull request by yuval-hazaz**
based on issue #1854

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@mshidlov are you including this in the next release?

**Comment by yuval-hazaz** [comment]
@mshidlov still waiting for your review

**Comment by mshidlov** [comment]
@yuval-hazaz can you please describe this PR, What is included (open an issue if needed or link an existing one)?

**Comment by mshidlov** [comment]
@yuval-hazaz 

This only generates comments for entities and not to all base files. are you ok merging it and creating part of the files override with the disclaimer and part without the disclaimer?

**Comment by yuval-hazaz** [comment]
@mshidlov thanks
I am good with merging current implementation
I will add a new FR to complete the missing parts

**Pull request merged**
