### PR TITLE
Added social media post for my contributions.

### PR DESCRIPTION
**Pull request by prakhar-198**
Issue Number: #4031 

## PR Details

 added social media posts on twitter and linkedIn telling about by my experience in contributing to amplication

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by souravjain540 — APPROVED** [review]

**Comment by prakhar-198** [comment]
Hey @souravjain540 how many points does this pr counts?

**Comment by souravjain540** [comment]
> Hey @souravjain540 how many points does this pr counts?

one

**Comment by souravjain540** [comment]
do you have another PR for blog?

**Comment by prakhar-198** [comment]
yes actually first I made pr for vlog it was merged. But on updating my forked branch it wasn't showing. If that's the case should I remove it from here?

**Comment by souravjain540** [comment]
> yes actually first I made pr for blog it was merged. But on updating my forked branch it wasn't showing. If that's the case should I remove it from here?

If that is merged, soon it will get showed to the main branch as well.

Please remove blog from here.

**Comment by prakhar-198** [comment]
Hey! @souravjain540 I'm facing some issue at my end while removing the blog file. If its possible at your end please remove it.

**Comment by prakhar-198** [comment]
> Hey! @souravjain540 I'm facing some issue at my end while removing the blog file. If its possible at your end please remove it.

You are goin to merge it right? @souravjain540

**Comment by abrl91** [comment]
@prakhar-198 please add a description of what this PR solve and the issue number

**Comment by prakhar-198** [comment]
> @prakhar-198 please add a description of what this PR solves and the issue number

Done!

**Comment by abrl91** [comment]
@prakhar-198 can you please resolve the conflict?
```
git checkout next
git pull origin next
git checkout <your-branch-name>
git merge next
```

**Comment by prakhar-198** [comment]
> #4031



> @prakhar-198 can you please resolve the conflict? I tried to resolve your conflict, but when I clicked on the commit button, GitHub warned me that the commit would be applied to the master branch.
> 
> I think there is a problem caused by the fact that you made your changes on the branch master of your fork. I think that the best approach, now that we have a conflict, is to reopen this PR, but this time, check out to a new branch from your fork.

Opened a PR #4184. Is that fine now? If some changes to be made do let me know.

**Pull request closed without merging**
