### PR TITLE
fix: add pagination for getOrganisationRepos

### PR DESCRIPTION
**Pull request by jainpawan21**
Issue Number: #2551

## PR Details

https://user-images.githubusercontent.com/39362422/188266026-a75bb107-e518-468d-b2cc-09e2253648e3.mov

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by alexbass86 — CHANGES_REQUESTED** [review]
It's a great addition, but this isn't the proper design or UX approach for pagination. Please allow me to prepare something that is aligned with our current design.

**Comment by jainpawan21** [comment]
@alexbass86 Any update on design?

**Comment by alexbass86** [comment]
> @alexbass86 Any update on design?
@jainpawan21  Here is the design, once again, thank you for your contribution :)
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=935%3A13277

Pagination

**Comment by yuval-hazaz** [comment]
@alexbass86 I don't think I understand from the design how it should work.
Did you mean we need to use infinite scroll? 
If yes, what is the DD on the top with the page number?

**Comment by alexbass86** [comment]
> @alexbass86 I don't think I understand from the design how it should work. Did you mean we need to use infinite scroll? If yes, what is the DD on the top with the page number?

My fault I forgot to remove the last comp in the design. It fixed now
we will have pages, not an infinity scroll

**Comment by jainpawan21** [comment]
Hi @alexbass86, thanks for design
I see limit (items per page is missing) or I should keep it constant?
and I see pageNo. is dropdown and it will take values from [1 ..... 120]? Isn't this will be too long list for dropdown?

**Comment by alexbass86** [comment]
> Hi @alexbass86, thanks for design I see limit (items per page) is missing or I should keep it constant? and I see pageNo. is dropdown and it will take values from [1 ..... 120]? Isn't this will be too long list for dropdown?

Yes, we will show only eight items per page
about the 120, I give you the edge case here with three numbers, but probably most users won't have more than two pages max :)

**Comment by jainpawan21** [comment]
Updated design as per figma:- 

https://user-images.githubusercontent.com/39362422/189209757-485ee37b-8857-4773-abf9-625ab5bc511c.mov

cc:- @alexbass86 @yuval-hazaz

**Comment by yuval-hazaz** [comment]
@jainpawan21 thanks!

@alexbass86 we can move forward with the current design, but I think there is something strange in the current behavior. I didn't see pagination with a single dropdown. Usually, at least "next" and "prev" buttons are provided. Since all users have no more than a few dozen of repos, the pagination is not for them - we can just use 50 or 100 items per page and solve the issue. 

This solution is for users with hundreds of repos - and for them, I think we just make it harder to use small pages ot 8 items and a drop-down to change pages. 

So I suggest using a larger page size (like 50) and moving forward. And then re-visit this page to consider any further needed improvements. 


@jainpawan21 please resolve the conflicts and use 50 for page size, and we will merge this PR

Thanks for your hard work 💜

**Comment by alexbass86** [comment]
> @jainpawan21 thanks!
> 
> @alexbass86 we can move forward with the current design, but I think there is something strange in the current behavior. I didn't see pagination with a single dropdown. Usually, at least "next" and "prev" buttons are provided. Since all users have no more than a few dozen of repos, the pagination is not for them - we can just use 50 or 100 items per page and solve the issue.
> 
> This solution is for users with hundreds of repos - and for them, I think we just make it harder to use small pages ot 8 items and a drop-down to change pages.
> 
> So I suggest using a larger page size (like 50) and moving forward. And then re-visit this page to consider any further needed improvements.
> 
> @jainpawan21 please resolve the conflicts and use 50 for page size, and we will merge this PR
> 
> Thanks for your hard work 💜

agree

**Comment by jainpawan21** [comment]
@yuval-hazaz Updated this PR with 50 as page size

**Review by yuval-hazaz — APPROVED** [review]
impressive work 👏

**Comment by tupe12334** [comment]
Wow @jainpawan21, great work on this issue!

**Pull request merged**
