### PR TITLE
create_social_post_astitva1100.md

### LINKED ISSUE #4031: Advocacy: Twitter Thread and Linkedin Post talking about Amplication.
In this issue, you have to write on both platforms:

- One Twitter Thread
- One Linkedin Post

Talking about your experience using Amplication or contributing to Amplication.

The content must provide some value to the community.

You have to tag Amplication on both platforms.

Linkedin: https://www.linkedin.com/company/67730467
Twitter: https://www.twitter.com/amplication

You have to create a file in PR with a link to both of your posts in the `tutorials` folder.

### PR DESCRIPTION
**Pull request by astitva0011**
Close #4031

## PR Details

 
 * I have created a thread on Twitter about amplication
 * I have posted a post on Linkedin about amplication

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by souravjain540** [comment]
@astitva0011 please make a separate PR for the social posts

**Comment by astitva0011** [comment]
seperate post for both platforms?

**Comment by astitva0011** [comment]
PR*

**Comment by souravjain540** [comment]
you have mixed two PRs into one.

One is for the changes you made in the code and other for the social posts.

please make a different PR for social posts.

**Review by souravjain540 — APPROVED** [review]

**Pull request merged**
