### PR TITLE
fix(side-menu-padding): padding between the sidemenu options fixed

### PR DESCRIPTION
**Pull request by codersrepo**
issue: #3933 
Fixed padding between options on entity page and Project Configuration Settings Page

### CODE REVIEW

**Comment by abrl91** [comment]
@codersrepo can you add the issue number to the PR description?

**Comment by abrl91** [comment]
run branch

**Review by abrl91 — APPROVED** [review]
@codersrepo well done!

**Comment by souravjain540** [comment]
need your email @codersrepo

**Comment by codersrepo** [comment]
> need your email @codersrepo

nabinakhadka55@gmail.com

**Pull request merged**
