### PR TITLE
partially fixed storybook

### PR DESCRIPTION
**Pull request by rolwin100**
Issue Number: N/A

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@rolwin100 thanks for your ongoing efforts! it is highly appreciated. 
I added you to the @amplication/committers group which will give you access to create branches and PRs directly on the repo

I will merge this branch into a local branch, so we can work together to resolve the missing parts

**Comment by yuval-hazaz** [comment]
@rolwin100 can you please resolve the conflict on the package-lock.json 
once you complete that, I will merge this PR to a new local branch to be able to work on it

**Comment by rolwin100** [comment]
will do it

**Comment by yuval-hazaz** [comment]
Thanks @rolwin100 
I will merge this PR, and we can continue work on the new branch

**Comment by rolwin100** [comment]
This PR can be closed

**Pull request merged**
