### PR TITLE
Feat (Plugins): Adds plugin categories as filter for ease of navigation

### PR DESCRIPTION
**Pull request by Abhi3685**
Close: #7109 

## PR Details

With plugin catalog becoming bigger, it would be nice to navigate more easily on the category type for all available plugins.
This PR adds category filter to plugins catalog for users to be able to view plugins for a particular category type.

Screenshot 2023-11-11 000327

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by Abhi3685** [comment]
Hi @barshimi, Did you get a chance to review my PR yet?

**Comment by mulygottlieb** [comment]
Hi @Abhi3685 
I'm sorry, but eventually, we implemented this internally in another PR, so I am closing this one. Thanks for your contribution and efforts!

**Comment by Abhi3685** [comment]
@mulygottlieb That's disheartening! Can I please have reference to the PR just for my understanding?

**Comment by mulygottlieb** [comment]
@Abhi3685 I apologize again. It was more complicated than we thought because the changes in the plugin-API should happen via the Amplication platform since the plugin-API service itself is a generated service by Amplication.

This is the PR: https://github.com/amplication/amplication/pull/7575, which is part of a bigger set of PRs that handled this.

**Comment by souravjain540** [comment]
Hi @Abhi3685 can you please DM me on discord?  We want to offer you some Amplication Swag as a token of appreciation for your hard work :)

**Pull request closed without merging**
