### PR TITLE
Fix/2259 update apollo server express package

### LINKED ISSUE #2259: 🐛 Bug Report: Updating the apollo-server-express package
### What happened?

We need to update the apollo-server-express package
I opened this issue to replace the renovate pr #2151 

### What you expected to happen

not relevant

### How to reproduce

not relevant

### Amplication version

0.11.3

### Environment

not relevant

### Anything else

_No response_

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by theamanbhargava**
Issue Number: #2259 

## PR Details

This fixes #2259 wherein apollo-server-express package needed to be updated across all packages. In this PR, apollo-server-packages has been updated to 3.6.1 for all packages and corresponding peerDeps have also been updated to match this version change.
This also updates the `typescript` version in dsg to match types updates in dependencies.
`instanceof` is now used instead of `error.constructor === SyntaxError` for more synctatical clarity

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

### CODE REVIEW

**Comment by theamanbhargava** [comment]
Are there any updates on this? Thanks in advance.

**Comment by yuval-hazaz** [comment]
@mshidlov what is the status of this PR?

**Comment by mshidlov** [comment]
hey @yuval-hazaz I assigned @tupe12334 to run tests for that change

**Comment by tupe12334** [comment]
Hi @theamanbharg good work! I have same questions.
Why did you didn't update the package-lock on the server and did update the entire package-lock on the dsg and update the package and package lock on the static files in the dsg?

**Comment by theamanbhargava** [comment]
Thanks Ofek 😀

Good question. AFAIR I think when I updated with latest base branch
version, I may have just forgotten to update that particular lock file
after resolving the conflict. Do you want me to try and update it now?

**Comment by tupe12334** [comment]
@theamanbhargava it ok if you want to update that or me, just let me know

**Comment by tupe12334** [comment]
@mshidlov can you please reopen this pr?

**Comment by yuval-hazaz** [comment]
@tupe12334 please handle this ASAP

**Comment by arielweinberger** [comment]
@tupe12334 What's the status of this one?

**Comment by tupe12334** [comment]
I update the @apollo/client dependencies because of an installation conflict

**Comment by tupe12334** [comment]
run branch

**Review by tupe12334 — APPROVED** [review]

**Pull request merged**
