### PR TITLE
User id added to generated token (base token & jwt token)

### PR DESCRIPTION
**Pull request by NisanAyash**
User id added to baseToken and jwtToken following this issue,
Complete details are available here #2491.

### CODE REVIEW

**Comment by tupe12334** [comment]
@barshimi and @yuval-hazaz, Please have a look at that, and how to implement that inside the new plugin system

**Comment by arielweinberger** [comment]
@NisanAyash Just to give you some context on why this might take a while to review and merge - we are introducing a plugin system and Auth (including JWT) will become a plugin in a separate code base.

@barshimi Is the owner of this plugin, so I'll get him to take a look and see if it's possible to potentially include in our auth plugin.

**Review by barshimi — APPROVED** [review]

**Comment by arielweinberger** [comment]
@barshimi @yuval-hazaz We can approve and merge this now, but I think we might want to port this change to the auth plugin. What do you think?

**Comment by arielweinberger** [comment]
@tupe12334 Can you please test this PR and make sure it works? Discussed with @yuval-hazaz, and we're happy to accept the contribution. We got to make sure it works.

**Comment by NisanAyash** [comment]
@arielweinberger @tupe12334 @barshimi 

Thank you all for accepting the contribution, 
I added one more change for the failing test.

By the way, let me know if I can help with the Auth plugin.

**Comment by tupe12334** [comment]
@NisanAyash Thanks for the contribution! can you please run the `update-test-data-service-snapshot` script in the `packages/amplication-data-service-generator/package.json` file to update the snapshot?

**Review by tupe12334 — APPROVED** [review]

**Comment by tupe12334** [comment]
run branch

**Comment by yuval-hazaz** [comment]
@tupe12334 let us know whether we can merge this

**Comment by arielweinberger** [comment]
Tested by @tupe12334 and good to merge!

Thank you very much @NisanAyash for your contribution. We appreciate it!

**Pull request merged**
