### PR TITLE
Added my Blog Post

### LINKED ISSUE #4006: Advocacy: Write a blog post about Amplication
We always promote non and low-code contributions to Amplication.

In this issue you have to write a blog post or article about the experience of using Amplication or make a tutorial that about any project using Amplication.

**The blog must include unique content based on your experience and not just a copy-paste from other blogs or Amplication web site.** 

This article should be published on any platform of your choice(for example, Medium, Dev. to, Hashnode, etc.).

You have to create a PR by making a new file(in which there is link to that article) in `tutorials` folder.

This contribution will count as **Two contributions** to the Amplication Hacktoberfest campaign.

### PR DESCRIPTION
**Pull request by hridaya423**
Close #4006 

## PR Details
Added my blog post: https://dev.to/learnearnfun/introduction-to-amplication-4k2i

## PR Checklist
- [X] Tests for the changes have been added
- [X] `npm test` doesn't throw any error

### CODE REVIEW

**Review by souravjain540 — CHANGES_REQUESTED** [review]
the blog is too short and not adding much value. please add and improvise

and I will review it again

**Comment by hridaya423** [comment]
Ok

**Comment by hridaya423** [comment]
@souravjain540 Any updates?

**Comment by hridaya423** [comment]
Hi @souravjain540, There's only 1 day left for hacktoberfest, Please review

**Review by souravjain540 — APPROVED** [review]

**Comment by hridaya423** [comment]
Could you please add the hacktoberfest labels (accepted, 2-pointer)

**Comment by hridaya423** [comment]
@souravjain540  please add the labels

**Comment by hridaya423** [comment]
@souravjain540 please could you add the labels!

**Comment by souravjain540** [comment]
> @souravjain540 please could you add the labels!

It is approved no need of labels

**Comment by hridaya423** [comment]
image
It still doesn't show up probably you have to merge it! @souravjain540

**Comment by souravjain540** [comment]
> image
> 
> It still doesn't show up probably you have to merge it! @souravjain540 

Don't worry. You'll get your reward.

**Comment by hridaya423** [comment]
ok

**Pull request merged**
