### PR TITLE
fix(amplication): grammar issues and unnecessary words

### PR DESCRIPTION
**Pull request by imperialc0der**
Cloe: #7120 
## PR Details

In the README.md file, there was some grammatical mistakes . Which i have fixed in my commit

### Summary
:memo::pencil2::sparkles:

Fix typos and grammar in `README.md` file.

> _The author of `README.md`_
> _Had some typos that needed to be shed_
> _So they made a pull request_
> _To fix the errors and the rest_
> _And now the file is clear and well-read_

### Walkthrough
* Fix grammatical error and typo in `README.md` ([link](https://github.com/amplication/amplication/pull/7117/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L77-R77), [link](https://github.com/amplication/amplication/pull/7117/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L188-R188))

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
hi @imperialc0der  thank you for your contribution.
For us to review this PR you must add the issue number in the description of the PR and make sure you were assigned to work on that issue

**Comment by imperialc0der** [comment]
Hey @yuval-hazaz my bad. i seemed to have not noticed that there was no issues regarding these grammar issues.
May i create one and send you the ID?

**Comment by souravjain540** [comment]
yes @imperialc0der

**Comment by imperialc0der** [comment]
Hey @souravjain540  my issue is #7120 . Please check.

**Review by abrl91 — APPROVED** [review]

**Review by abrl91 — APPROVED** [review]

**Comment by souravjain540** [comment]
@imperialc0der can you please dm me your email on discord for the swag?

**Comment by imperialc0der** [comment]
@souravjain540 done . my username is omim786.

**Pull request merged**
