### PR TITLE
feat(client): version number on workspace header to link to github releases

### PR DESCRIPTION
**Pull request by DanielLai20**
Close: #7051

### Summary
:link::octocat::memo:

Changed the version button in the workspace header to a link to the releases page on GitHub. This provides more information about Amplication versions and release notes.

> _`Version` button changed_
> _Opens GitHub releases page_
> _Winter of updates_

### Walkthrough
* Change the version button to a link that opens the releases page on GitHub in a new tab ([link](https://github.com/amplication/amplication/pull/7094/files?diff=unified&w=0#diff-7fdb758d72b986ee99ae091fcd9f9b1312ecd063170e9dcbd9d99d5f47812d24L197-R215))

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
hi @DanielLai20  for us to review this PR you must add the issue number in the description of the PR and make sure you were assigned to work on that issue

**Review by yuval-hazaz — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
Thanks, well done!

**Comment by yuval-hazaz** [comment]
@DanielLai20  to fix the formatting error please run `npx nx format:write` and commit the changes

**Comment by levivannoort** [comment]
@DanielLai20 QA'd how the change works and it is as expected. Please run the `npx nx format:write` command and commit + push the changes so we can accept the pull request.

**Comment by souravjain540** [comment]
@DanielLai20 can i get your email on discord for the swag?

**Comment by DanielLai20** [comment]
@souravjain540 yes! daniel.lai9798@gmail.com

**Pull request merged**
