### PR TITLE
Admin-ui entity create and update field for to-many relations

### LINKED ISSUE #1381: DSG: API & Admin-UI - add support for many-to-many navigation in EntityFindMany
Based on #1379 

The dataProvider currently expects the relationship to be based on entityId on the "many" side.
for example 1 customer with many orders

```
orders(
   where:{
      customerId:"xxxxx"
   }
)
```

But, when the relationship is many-to-many - the correct way to create the query is 
```
products(
   where:{
      categories:{
         some:{
            id:"xxx"
         }
      }
   }
)
```

for this query to work - we need to implement the following changes:
1) Add new search property on `EntityWhereInput` for many-to-many fields (currently this field is not generated). In Prisma this field uses the type `[Entity]ListRelationFilter`
2) update `ra-data-provider-amplication` to map the query correctly

### LINKED ISSUE #2225: 🐛 Bug Report: many-to-many relation is not support in the admin UI
### What happened?

many-to-many relation is not support in the admin UI

### What you expected to happen

The user should be able to create, update, and view data with many-to-many relations in the admin UI

### How to reproduce

Create a many-to-many relation and open the admin UI

### Amplication version

0.11.1

### Environment

n/a

### Anything else

related to #2223 

### Are you willing to submit PR?

_No response_

### Code of Conduct

I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abrl91**
resolve #2225

On admin UI, added the ability to make a reference between two entities in a form of many to many (one to many from the entity perspective).
For example, one article can have many tags, and one tag can appear in more than one article (many tags can appear on many posts...)

To make it works I added the following block code on the edit entity and create an entity files (post and tag for the example):

```
<ReferenceArrayInput
          source="tags"
          reference="Tag"
          parse={(value: any) => value && value.map((v: any) => ({ id: v }))}
          format={(value: any) => value && value.map((v: any) => v.id)}
        >
          <SelectArrayInput optionText={TagTitle} />
 </ReferenceArrayInput>
```

For this feature to work I realized that the `source` needs to be plural, therefore I wrap it on the code generation with 'pluralize'

image

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@abrl91 please update the description of the PR and add details on what this PR is doing, what was changed and what use cases are supported not

**Comment by abrl91** [comment]
@yuval-hazaz I updated the description. Also, I realized that the source attribute must be plural for this feature to work. Without 'pluralize', when trying to edit and save a post with its tags, it doesn't get saved correctly

**Review by yuval-hazaz — APPROVED** [review]

**Comment by mshidlov** [comment]
@yuval-hazaz Has it been tested on staging?

**Comment by abrl91** [comment]
@mshidlov @yuval-hazaz 
I converted this PR to a draft as we decided to first upgrade and update our ra-data-graphql-amplication package
because the current version leads to a dependency-hell.
https://github.com/amplication/amplication/issues/2376

**Comment by abrl91** [comment]
@yuval-hazaz @mshidlov 
I checked out from 0.12.2 to a brand new branch and started over this task.
You can review my pr https://github.com/amplication/amplication/pull/2456
We can close this pr. Should I do it?

**Comment by mshidlov** [comment]
@abrl91 if this is not relevant any more yes you should close it

**Comment by abrl91** [comment]
Opened new PR for the issue https://github.com/amplication/amplication/pull/2456

**Pull request closed without merging**
