### PR TITLE
fix(client): fixed hover behavior over last commit sha

### PR DESCRIPTION
**Pull request by rielAsh24**
Fix for #5846

Close: #5846

## PR Details

Have added changes to the last commit sha. The current behavior results in no tooltip on mouse hover as mentioned in #5846 expected results.

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by rielAsh24** [comment]
@abrl91 Hey! Wish to request for a review as the fix suggests I would require one.

**Comment by abrl91** [comment]
@rielAsh24 it was already fixed

**Comment by rielAsh24** [comment]
@abrl91 No worries! Excited to contribute, will continue to work on other issues

**Comment by abrl91** [comment]
@rielAsh24 Thank you 💪
so, I'll close this PR

**Comment by abrl91** [comment]
duplicate PR for the same issue

**Pull request closed without merging**
