### PR TITLE
Fix conflicting flags

### LINKED ISSUE #2100: 🐛 Bug Report: Conflicting options in Amplication's CLI
### What happened?

There is a conflicting option in the Amplication's CLI (`entities:fields:update`)

The option for setting field and format has the same shortcut (`-f`).

### What you expected to happen

```
$ amp entities:fields:update --displayName "Creation Date" -f ckxt0rbjj8294951bs645fkdmr1
 ›   Error: Expected --format=ckxt0rbjj8294951bs645fkdmr1 to be one of: JSON, styledJSON, table
 ›   See more help with --help
```

The `-f` flag was supposed to be treated as `field`

### How to reproduce

1. Open a terminal
2. Type `amp entities:fields:update --displayName "When was it created" -f ckxt0rbjj8294951bs645fkdmr1`
3. See the error (The `-f` flag was meant for field but it is treated as for `--format`)0.

### Amplication version

0.1.4

### Environment

-

### Anything else

_No response_

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0xsapphir3**
Closes #2100 

I have currently set the flag to `-z`. If you want me to change it then comment and I will make the edit ;)

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
Thanks for catching this! 
I don't think Z is the correct selection for this param. 

I suggest that instead of -z we use `-i` 

It can be related to the first letter in "ID" and the second letter in "field"

**Comment by AsianCat54x** [comment]
Ah totally makes sense. I should replace `-z` with `-i`

**Review by yuval-hazaz — APPROVED** [review]

**Comment by mshidlov** [comment]
@yuval-hazaz is this can be merged? do we need docs update for that?

**Comment by yuval-hazaz** [comment]
You can merge
docs should be updated automatically before deploying to npm

**Pull request merged**
