### PR TITLE
feat(client): Edit entity via ERD

### PR DESCRIPTION
**Pull request by Sheersendu**
Close: #6683 

### Summary

Now Entity can be edited from ERD view. ERD view is preserved after an entity is edited.

### Walkthrough
 * Added pencil icon to navigate to individual entity 
 * Used default checked option for toggle to preserve ERD view post entity edit  

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by Sheersendu** [comment]
Can it be kindly reviewed? @gitstart

**Comment by Sheersendu** [comment]
@overbit will it be possible within your bandwidth to review this PR kindly? Its pending for a long time now.

**Comment by overbit** [comment]
@Sheersendu sure, please merge `next` into your branch so the conflicts will be resolved and we can proceed with the merge process.

**Comment by Sheersendu** [comment]
Hi @overbit , merge conflicts has been resolved and pushed. Kindly confirm once when possible and do let me know if further changes are required :)

**Comment by overbit** [comment]
@Sheersendu running tests and merging! Well done sir!

**Review by overbit — APPROVED** [review]

**Comment by Sheersendu** [comment]
Hi @overbit resolved issues, kindly let me know if anything further is required from my side :)

**Pull request merged**
