### PR TITLE
Update the width of <hr/> tag

### PR DESCRIPTION
**Pull request by Himanxu1**
Improve the UX by decreasing the width of <hr/> tag

Issue Number: #3604

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by Himanxu1** [comment]
Did i do something wrong ? @EugeneTseitlin

**Comment by souravjain540** [comment]
@EugeneTseitlin, please always brief the community member on everything before closing their PR.

**Comment by EugeneTseitlin** [comment]
@Himanxu1 @souravjain540 I didn't mention to close the PR, the branch 15 was created by mistake, so I deleted it. Sorry for this occasion and keep doing a great work!

**Comment by souravjain540** [comment]
please review @abrl91

**Comment by arielweinberger** [comment]
@Himanxu1 Can you please include a screenshot so we can familiarize ourselves with the "before and after"?

**Comment by Himanxu1** [comment]
Here 
before : 

ss1

after: 
ss2

**Comment by alexbass86** [comment]
> Here before :
> 
> ss1
> 
> after: ss2

Great job!! @Himanxu1

**Comment by arielweinberger** [comment]
@Himanxu1 I've set the base branch to master. Otherwise, if we release 0.15.3, your PR will be automatically closed again.

Please resolve any conflicts, and when done, we'll be happy to merge your contribution!

**Comment by souravjain540** [comment]
@Himanxu1 please resolve conflicts

**Comment by Himanxu1** [comment]
How can i do that ??

**Comment by abrl91** [comment]
> How can i do that ??

merge branch master to your branch and resolve the conflict in packages/amplication-client/src/Application/git/GitActions/ExistingConnectionsMenu.scss

```
git checkout origin master
git pull
git checkout <your branch name>
git merge origin master
```
resolve the conflict 
then
```
git add .
git merge --continue
git push
```

**Comment by yuval-hazaz** [comment]
@Himanxu1 please let us know if you need any additional help

**Comment by yuval-hazaz** [comment]
@Himanxu1 I am closing the PR for now, please feel free to send a new PR once you are ready 
Thanks

**Pull request closed without merging**
