### PR TITLE
feat(client): add support for static website deployment

### PR DESCRIPTION
**Pull request by overbit**
Fixes : https://github.com/amplication/amplication-infrastructure-next/issues/50

## PR Details

Replace the injectEnvVariables.js with nx build configurations to build the client application with the correct variables per environment.
The injectEnvVariables related scripts, nx target `docker:build` and Dockerfile will be deleted as soon as we complete the migration to the new static website setup.

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by levivannoort** [comment]
I'm in the midst of adding the ci/cd part for this to this pull request. If it can be detached separately, let me know @overbit

**Comment by overbit** [comment]
Sure thing

**Review by EugeneTseitlin — APPROVED** [review]

**Comment by levivannoort** [comment]
As talked about before I would still be up for keeping the Dockfiler for the client even though it isn't used in production when moving of to the cdn.

**Comment by levivannoort** [comment]
Added the ci/cd part as a pr to this branch, so should auto update to be merged to next when this is merged.

**Review by levivannoort — APPROVED** [review]

**Pull request merged**
