### PR TITLE
bug(client): links fixed in the Login.tsx

### PR DESCRIPTION
**Pull request by KlausMikhaelson**
Issue Number: N/A

## PR Details
Links fixed for the api and graphql in login.tsx

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by arielweinberger** [comment]
Hey @KlausMikhaelson - I see your previous PR (#3344) was closed, not sure why.

Copy-pasting my reply here:

The tests are failing due to snapshot mismatch. On your branch, can you please run:
```
$ lerna run --scope @amplication/data-service-generator update-test-data-service-snapshot
$ lerna run --scope @amplication/data-service-generator test
```

Then once all tests are passed, please commit the new snapshot. The CI workflow should then pass (I hope).

**Comment by KlausMikhaelson** [comment]
@arielweinberger Okay thank you

**Comment by abrl91** [comment]
> Hey @KlausMikhaelson - I see your previous PR (#3344) was closed, not sure why.
> 
> Copy-pasting my reply here:
> 
> The tests are failing due to snapshot mismatch. On your branch, can you please run:
> 
> ```
> $ lerna run --scope @amplication/data-service-generator update-test-data-service-snapshot
> $ lerna run --scope @amplication/data-service-generator test
> ```
> 
> Then once all tests are passed, please commit the new snapshot. The CI workflow should then pass (I hope).

@arielweinberger I am trying to help him with that but the snapshot script throws an error

**Comment by abrl91** [comment]
@arielweinberger 
image

**Comment by arielweinberger** [comment]
run branch

**Comment by arielweinberger** [comment]
@KlausMikhaelson We're sorry to see you're facing some issues doing this. We are not sure why that happens, and will investigate further.

We managed to generate the snapshots for you, and merge them. Thank you so much for your contribution!

@souravjain540 Let's get to meet @KlausMikhaelson better? ;)

**Comment by KlausMikhaelson** [comment]
@arielweinberger  @abrl91  Thank you so much for helping me out ! really pumped up to contribute more  !

**Pull request merged**
