### PR TITLE
side menu icon size change and color of icon

### PR DESCRIPTION
**Pull request by AayKaay**
Issue Number:  #2712 

## PR Details
Decreased the font size and changed the background color of icon div based on the figma file shared in the issue 

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

### CODE REVIEW

**Review by yuval-hazaz — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
@tupe12334 can you please resolve the conflict on this PR (package-lock)?

**Comment by tupe12334** [comment]
create branch

**Comment by tupe12334** [comment]
run branch

**Comment by tupe12334** [comment]
@AayKaay Please have a look at that image, the icons are not centered inside the box.

Screen Shot 2022-08-15 at 8 49 34

**Comment by tupe12334** [comment]
You can do it in many ways.
The simple one is to set the height to `auto`

**Review by tupe12334 — APPROVED** [review]

**Comment by AayKaay** [comment]
Should I close this issue now?

**Pull request merged**
