### PR TITLE
fix(amplication): misc:twitter Logo and Hover Badge Enhancement in Readme

### PR DESCRIPTION
**Pull request by PentesterPriyanshu**
added new hover badges of twitter which is now called X , added logos of discord and youtube in the existing hoverbadges

Close:  #7355

### Summary
🎨📝🚀

This pull request updates the `README.md` file to make the badges more consistent and attractive. It is a minor cosmetic improvement for the amplication/amplication repository.

> _`README.md` shines_
> _Badges with consistent style_
> _Autumn of web apps_

### Walkthrough
*  Update badges in the README.md file to use consistent height, logo and style ([link](https://github.com/amplication/amplication/pull/7342/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L16-R37))

Screenshot from 2023-10-27 19-13-38

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
@abrl91 can you tell about this, i am also working improving ui of amplification

**Comment by overbit** [comment]
@PentesterPriyanshu please make sure your pull request adheres to the [contribution guidelines](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md). We'll need an issue to be created for this pull request as well so that the change can be attached to the applicable issue.

**Comment by PentesterPriyanshu** [comment]
@overbit , please review it now

**Comment by PentesterPriyanshu** [comment]
@overbit , please review it now

**Review by abrl91 — APPROVED** [review]

**Comment by souravjain540** [comment]
@PentesterPriyanshu please dm me your email on discord for swag

**Comment by PentesterPriyanshu** [comment]
@souravjain540  my mail is this i can dm you in discord too priyanshu.prajapati1112@gmail.com

**Pull request merged**
