### PR TITLE
fix(client): added type safety for urlError

### PR DESCRIPTION
**Pull request by rolwin100**
Issue Number: #2614

## PR Details

Fixed issue regarding typescript error on Login.tsx at line 91

### CODE REVIEW

**Comment by souravjain540** [comment]
Thanks for the PR :)

**Comment by tupe12334** [comment]
@rolwin100 Thanks for the pr, just for you to know, this doesn't type safety, you are not checking if it's a string, you declare it as a string.
And please check my review of the branch name to @molaycule in https://github.com/amplication/amplication/pull/2612#issuecomment-1104186444

**Comment by rolwin100** [comment]
@tupe12334 can you pls tell me what can be done about this.

**Comment by tupe12334** [comment]
The root of the problem is from lines 65-70 when you generate the urlError, we don't check that the ```params.error``` is a string and only string so the declare type is ```string | (string | null)[] | null``` a bit confusing but it means string or null or array of string or null, so we need to check if the error is string there and if not return a null
@rolwin100

**Pull request closed without merging**
