### PR TITLE
feat: add health check endpoint in amplication-server

### LINKED ISSUE #2192: Add Health Check(s) to @amplication/server
It's good practice to include a health check with your services. This is specifically important when deploying to systems like Kubernetes where it can handle traffic routing based on healthy endpoints/services. 

NestJS has this already figured out and provides a set of [Health Checks](https://docs.nestjs.com/recipes/terminus#healthchecks-terminus) available.

Some health-checks `@amplication/server` could benefit from is...
1. `HttpHealthIndicator` - A basic HTTP endpoint to report that server that is listening on a port is running and accepting requests.
2. `TypeOrmHealthIndicator` / `SequelizeHealthIndicator` - Reports that the server is connected to external database(s) - Useful in case the server can no longer connect to the DB and Kubernetes can stop routing traffic to the service.
3. `DiskHealthIndicator` - Reports when Disk Space for a specific volume/mount is low - Could be useful for Amplication - maybe not?

### PR DESCRIPTION
**Pull request by nya1**
Closes #2192

## PR Details

In amplication-server added new health check endpoint `GET /_health/live`, it returns `HTTP 204` (No content) when the server is up and running.

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

### CODE REVIEW

**Review by tupe12334 — APPROVED** [review]

**Comment by tupe12334** [comment]
@nya1 Please run the format script from the server/package.json

**Comment by nya1** [comment]
> @nya1 Please run the format script from the server/package.json

done

**Comment by tupe12334** [comment]
@yuval-hazaz @mshidlov Did it stand for your desired specifications for the health endpoint path?
```/_health/live```

**Comment by yuval-hazaz** [comment]
perfect, let's merge

**Pull request merged**
