### PR TITLE
Precommit hooks

### LINKED ISSUE #4384: Git hooks that run code format and lint
### Feature description

It would be nice to have these two hooks to ensure that we don't forget to format code before commit. Otherwise CI fails and make you format code, commit and push again, but it's time consuming. I've forgot about it so many times, and I've also seen others commits with description "format code", which means I'm not the only one. This improvement is going to save us a lot of time.  

### Use case

_No response_

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by EugeneTseitlin**
Close #4384

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by arielweinberger — CHANGES_REQUESTED** [review]
I don't think the DSG package-lock.json change should be included in this PR.
Also, please ensure you add a description to the PR detailing the solution, and follow our branch naming convention. In this case, should be a `chore/` prefix.

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin please see the comments

**Comment by EugeneTseitlin** [comment]
@arielweinberger I agree regarding DSG package-lock, I reverted this change. Branch name I don't change now, but keep it in mind for the next time.

**Comment by overbit** [comment]
We might want to make it more clear of what is running against since without any explicit `base` param, the affected list of projects to format will be generated comparing the HEAD with the `main` / `master` locally. 

https://nx.dev/nx/format-write 

Let's either use `npx nx format:write --all` or specify the correct base branch (more complicated) 
@EugeneTseitlin

**Pull request merged**
