### PR TITLE
Updated field error messages to be more user friendly

### LINKED ISSUE #4012: Enhancement: Make field error messages more user-friendly
### Feature description

Currently, when trying to rename a service/project and inserting an empty value, the error looks like this:
image

While the error message is clear, I believe it can be more professional and user friendly. 
- First of all, "NOT" being capitalized comes across agressive.
- Secondly, error messages commonly say _what is expected_ rather than _what is wrong_.
 
Instead of `must NOT have fewer than 2 characters` the message should be `Must be at least 2 characters long`.

If you can, please go through the repo and apply this change wherever applicable (a simple search of "must NOT" in our repo reveals a few more occurences).

We would happily help you with error messages if needed.

### Use case

_No response_

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by Ahtritus**
Close #4012 

### Enhancement: Make field error messages more user-friendly

Using `ajv-errors` to have custom user friendly messages for field error messages

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by abrl91** [comment]
run branch

**Review by abrl91 — CHANGES_REQUESTED** [review]
@Ahtritus it looks good!
The only thing I recommend doing is to add a constant in `packages/amplication-client/src/util/formikValidateJsonSchema.ts`

```
export const validationErrorMessages = {
  AT_LEAST_TWO_CHARARCTERS = "Must be at least 2 characters long"
} 
```

And import it in all the other files, for example: `packages/amplication-client/src/Profile/ProfileForm.tsx`

```
import { validate, validationErrorMessages } from "../util/formikValidateJsonSchema";
cosnt { AT_LEAST_TWO_CHARARCTERS } = validationErrorMessages
```

Then, use it:
```diff
  errorMessage: {
    properties: {
      displayName: AT_LEAST_TWO_CHARARCTERS,
      name: AT_LEAST_TWO_CHARARCTERS,
      pluralDisplayName: AT_LEAST_TWO_CHARARCTERS,
    },
  },
```

**Comment by Ahtritus** [comment]
> @Ahtritus it looks good! The only thing I recommend doing is to add a constant in `packages/amplication-client/src/util/formikValidateJsonSchema.ts`
> 
> ```
> export const validationErrorMessages = {
>   AT_LEAST_TWO_CHARARCTERS = "Must be at least 2 characters long"
> } 
> ```
> 
> And import it in all the other files, for example: `packages/amplication-client/src/Profile/ProfileForm.tsx`
> 
> ```
> import { validate, validationErrorMessages } from "../util/formikValidateJsonSchema";
> cosnt { AT_LEAST_TWO_CHARARCTERS } = validationErrorMessages
> ```
> 
> Then, use it:
> 
> ```diff
>   errorMessage: {
>     properties: {
>       displayName: AT_LEAST_TWO_CHARARCTERS,
>       name: AT_LEAST_TWO_CHARARCTERS,
>       pluralDisplayName: AT_LEAST_TWO_CHARARCTERS,
>     },
>   },
> ```

Done!

**Review by abrl91 — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
@Ahtritus nice work 💜

**Pull request merged**
