### PR TITLE
docs(auth): add documentation for github auth

### PR DESCRIPTION
**Pull request by overbit**
## PR Details

Add documentation about github authentication flow and  instructions for local development setup

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]
@overbit we manage the docs on a separate repo https://github.com/amplication/docs which is automatically published to https://docs.amplication.com/docs/

Please move the content to the docs repo and let's review it over there.

**Comment by overbit** [comment]
> @overbit we manage the docs on a separate repo https://github.com/amplication/docs which is automatically published to https://docs.amplication.com/docs/
> 
> Please move the content to the docs repo and let's review it over there.

Just notices that we indeed have some docs around the same topic here https://docs.amplication.com/docs/connect-server-to-github. I'll update this there and leave this PR to only refactor the client var name.

**Comment by yuval-hazaz** [comment]
@overbit thanks! Please note that the existing doc is not in a good shape and needs an update, so please use the content from this PR to update it so we won't lose the knowledge

**Comment by overbit** [comment]
Docs migrated to correct repo https://github.com/amplication/docs/pull/213
Refactoring issue open to address environment variable naming https://github.com/amplication/amplication/pull/4383

Closing this issue

**Pull request closed without merging**
