### PR TITLE
Fix/3891 fix build page responsive

### PR DESCRIPTION
**Pull request by evansnguyen**
Close: #3891

## PR Details

Fix 2 bugs related to styles of Actions log of the Build Page: 
- Horizontal scroll bar misplaced: 
  - Found out the issue was this page inherit `overflow: auto` from the content page. overflow-x was incorrectly set when the user resized the window size at the responsive point.
  
 - Page responsive: update min-width from 500px to 360px which will fix responsive issue
 class `.log-container` was only used in `BuildPage` so I move the style class from PageContent to BuildPage
## PR Checklist

- [ ] ~Tests for the changes have been added~
- [ ] ~`npm test` doesn't throw any error~

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by Aadarsh805 — COMMENTED** [review]
this is great, I was trying to figure this out

**Comment by yuval-hazaz** [comment]
thanks @evansnguyen for your first contribution 😍
We will review the PR soon and will include it in the next release once it is approved

**Comment by yuval-hazaz** [comment]
@EugeneTseitlin please review

**Comment by souravjain540** [comment]
@EugeneTseitlin  please review

**Review by EugeneTseitlin — APPROVED** [review]

**Comment by EugeneTseitlin** [comment]
@evansnguyen Thanks for contribution!

**Pull request merged**
