### PR TITLE
feat(client): add entity relationship diagram (ERD) view

### PR DESCRIPTION
**Pull request by mohammed-bahumaish**
## PR Details

Closes: #6610

This PR contains:

- [X] Viewing Entities and Entities Fields as ERD.
- [X] Auto layout.

### CODE REVIEW

**Comment by overbit** [comment]
@mohammed-bahumaish Thanks for the contribution!
Could you please address the CI failure by running `npx nx format:write` ?

**Review by overbit — CHANGES_REQUESTED** [review]
@mohammed-bahumaish Thanks for the contribution!
Could you please address the CI failure by running `npx nx format:write` ?

**Comment by mohammed-bahumaish** [comment]
Thanks @overbit ,
I hope this fixes it. Let me know if there is something else needs to be done.

**Review by overbit — APPROVED** [review]
Really good work @mohammed-bahumaish 💯 !

**Comment by mohammed-bahumaish** [comment]
Thanks @overbit , I'll fix that issue soon.

**Pull request merged**
