### PR TITLE
[2347] - App New Project Screen

### PR DESCRIPTION
**Pull request by muhsinkamil**
Issue Number: https://github.com/amplication/amplication/issues/2347

## PR Details

- Implementation of new app screen.
- Currently, all the options are in the single screen. This PR divides the options to two screens with some transition 🚀  

## PR Checklist
- [x] `npm test` doesn't throw any error

## Further comments

- We can rename the filename from "CreateAppFromExcel.tsx" -> "NewApp.tsx"
On renaming, Git might show everything is newly added, which may not be ideal for the reviewers to check what has changed. Hence, did not change that. Please let me know if I can proceed to change the filenames after the review 🚀 

## Screenshot

https://user-images.githubusercontent.com/62111075/161519311-14bd333c-8361-4ed7-bdf9-8f91498ef27d.mov

### CODE REVIEW

**Comment by mshidlov** [comment]
Hey @muhsinkamil thank you for sending that PR, is it still a draft? or is it ready to be merged?

**Comment by muhsinkamil** [comment]
@mshidlov It's still a draft. Just need a final finish. Will make it ready for review after little refactors :)

**Comment by mshidlov** [comment]
@muhsinkamil Thank you we are planning to add it to `0.12.4` this week if we will manage it will be great if not we will include it in the next release.

**Comment by muhsinkamil** [comment]
@mshidlov Thank you, Planning to wrap up tomorrow, Should be good to go for this week  🤞

**Comment by yuval-hazaz** [comment]
@muhsinkamil This looks great!! thanks for the great job,
We will review the code soon, and @alexbass86 will review the results.

**Comment by yuval-hazaz** [comment]
@muhsinkamil before I add comments on specific items - I see that you use a lot of hard-coded sizes, especially for font-size and line-height. 
Instead, would you please use @include 

e.g:
      @include title1;
      @include headline1;



If there is no @mixin available with the specific style, you should either use the closest one ot create a new one - please consult with @alexbass86 

I know that @alexbass86 updated some of the font-sizes in the design system, so maybe some styles in the mixins are not updated. In order to update it, we should test the impact on the entire system - so instead, we should use the existing mixin with the closest style and when we update the design system it will impact the entire system including these new changes

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]
@muhsinkamil before I add comments on specific items - I see that you use a lot of hard-coded sizes, especially for font-size and line-height.
Instead, would you please use @include

e.g:
@include title1;
@include headline1;

If there is no @mixin available with the specific style, you should either use the closest one ot create a new one - please consult with @alexbass86

I know that @alexbass86 updated some of the font-sizes in the design system, so maybe some styles in the mixins are not updated. In order to update it, we should test the impact on the entire system - so instead, we should use the existing mixin with the closest style and when we update the design system it will impact the entire system including these new changes

**Comment by muhsinkamil** [comment]
@alexbass86  I tried using the available mixin for font-sizes and weights but that does not match the figma design. 
So our option would be,
   1. To create custom mixin for this specific screen
   2. Or, To modify figma to match the existing design in other pages. 
   
I think, creating custom mixins for this screen should be fine. The reason being as @yuval-hazaz said, modifying existing mixin would impact other page designs. 
What's your vote on this ?

**Comment by alexbass86** [comment]
> @alexbass86 I tried using the available mixin for font-sizes and weights but that does not match the figma design. So our option would be,
> 
> 1. To create custom mixin for this specific screen
> 2. Or, To modify figma to match the existing design in other pages.
> 
> I think, creating custom mixins for this screen should be fine. The reason being as @yuval-hazaz said, modifying existing mixin would impact other page designs. What's your vote on this ?

Hi, first of all, fantastic job! So thank you so much for this contribution.
Few missing parts:
1. on hover, you should add a drop shadow, and the gif needs to be in opacity (text is on top of the img please make sure)
you can see the exact effect in the prototype 
https://www.figma.com/proto/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?page-id=16%3A3154&node-id=163%3A4044&viewport=401%2C48%2C0.36&scaling=min-zoom&starting-point-node-id=163%3A4044
2. Regarding the font thing, here is the link for updated design with current amplication font styles:
- "Welcome to amplication" - Use "sectionTitle" (17px)
- "Let’s start building your app" - Use "headline1" (40px)
- "Start from" - Use "sectionTitle" (17px ,700 weight)
- "Scratch", "Sample App" - Use font name DM Mono, "pageTitle" (24px 500 weight)
- "Just upload an Excel or CSV.." - Use "body2" (12px)
- inside the excel page "Start with schema from excel" - Use "pageTitle" (24px 700 weight)
- "Start building your application..." - Use "body1"
- inside the drag and drop box - Use "body2" (12px)

please let me know if you have issues

**Comment by muhsinkamil** [comment]
@alexbass86 / @yuval-hazaz Thanks for the review. I have replaced with mixins and added on:hover styles to options. Please check

**Comment by alexbass86** [comment]
@muhsinkamil I don't see you placed the gifs & added the hover effects i miss something? also the "back button" should be on top

image

this is the design 
A

**Comment by muhsinkamil** [comment]
@alexbass86 
- Isn't the gif not displayed on hovering the card ? 🤔
- I did not change styles on back button since it was already there. Let me check and  try changing this button position.

**Comment by alexbass86** [comment]
> @alexbass86
> 
> * Isn't the gif not displayed on hovering the card ? 🤔
> * I did not change styles on back button since it was already there. Let me check and  try changing this button position.

Hey, nope, I don't see the gifs on hover also seems that the hover drop shadow effect is not working.

**Comment by alexbass86** [comment]
@muhsinkamil  Hi, any update :) if you have any troubles please let us know

**Comment by muhsinkamil** [comment]
Hey @alexbass86 Thanks. Away today. Will update you tomorrow. Maybe by discord if I have any questions

**Comment by muhsinkamil** [comment]
@alexbass86 Could you please take a recent pull and check again. I think your screenshot is on old commit id.
Please find the attached recording from the recent pull.

https://user-images.githubusercontent.com/62111075/163105413-b1e96932-73a1-4e08-9eeb-30295a483f40.mov

**Comment by alexbass86** [comment]
> @alexbass86 Could you please take a recent pull and check again. I think your screenshot is on old commit id. Please find the attached recording from the recent pull.
> 
>  Screen.Recording.2022-04-13.at.10.45.08.AM.mov

Looks good!!! you forgot to put an easing effect on the hover as the drop shadow appears without any animation, but we can fix it in the future @tupe12334 @mshidlov

**Review by yuval-hazaz — APPROVED** [review]

**Pull request merged**
