### PR TITLE
feat(repository): Issue 1862 : Add a PR Template

### PR DESCRIPTION
**Pull request by Rutam21**
# Linked Issue
It fixes https://github.com/amplication/amplication/issues/1862

# Description
This PR updates the `PR Template` for this repository to use the latest Github Issue forms.

# Methodology
A respective `yaml` file has been added that would be used to provide the newest template for any PR.

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@Rutam21 thanks

@mshidlov please review the template

**Comment by mshidlov** [comment]
Thank you @Rutam21 I will review it soon

**Comment by yuval-hazaz** [comment]
We already implemented another version of the template

**Comment by yuval-hazaz** [comment]
@all@all-contributors please add @Rutam21  for docs

**Pull request closed without merging**
