### PR TITLE
feat: client demo app

### PR DESCRIPTION
**Pull request by thucpn**
I create a sample blog built by Amplication and NextJs.
Live demo: https://amplication-client-demo.vercel.app

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@thucpn awesome work 👏

Where is the server is hosted? 

Can you share a link to the repo with the code generated by Amplication?

Can you share a link to the repo with the code for the client that connects to the server?

**Comment by thucpn** [comment]
@yuval-hazaz I just made an update on markdown file. Server host, client repo, server repo were included. Please take a look 😀

**Comment by yuval-hazaz** [comment]
Thank @thucpn 
I see that the server is running on the sandbox environment which goes down after 30 days of inactivity.
I will look for a way to flag this environment so it will not be removed. 

For a more permanent solution, it would be awesome to deploy the server on Heroku or any other PaaS.

Let me know if you are up for the challenge.

@all-contributors please add @thucpn  for example

**Comment by yuval-hazaz** [comment]
@thucpn 
You are eligible for two credits toward our hacktoberfest challenge (as described here https://github.com/amplication/amplication/issues/1754).
So, you can already get a sticker pack, and with two more credits, you can also get a T-shirt. 

To get the credits for the challenge please post a link to this PR on the `hacktoberfest` channel on our Discord server 

https://discord.gg/KSJCZ24vj2

**Comment by yuval-hazaz** [comment]
one more thing I just noticed, the link to "Admin Dashboard" on the home page is not linking to the correct address
image

**Comment by thucpn** [comment]
Thanks @yuval-hazaz , I fixed it.

**Comment by kernelogic** [comment]
Does Amplification now support deploy to Vercel directly?

**Pull request merged**
