### PR TITLE
Fix/3653 text overflow issues

### PR DESCRIPTION
**Pull request by evansnguyen**
Close: #3653

## PR Details

Fixing minor problems with long projects/services' name

Add EllipsisText component:
- 2 modes: click, hover
- maxHeight: to handle long text wrapped in a limited height container. (example: banner in ResourcesHome or suggestions in CommandPallete)
- maxLength: to handle the length of text.

Add hook useTextOffsetHeight:
- to detect when text is longer than one line (text height is greater than a threshold).
- usage: I use this hook to align the item for the header of the Resource Card. If the repo name within 1 line then align center else align to start (screenshot below)

Fixes screenshots:
Resource Card:
image
Resources Home:
image
Command pallete:
image

## PR Checklist

~- [ ] Tests for the changes have been added~
~- [ ] `npm test` doesn't throw any error~

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by evansnguyen** [comment]
I'm having trouble spinning up project v1.1.2
I end up working on v1.1.0 tags on amplication repo for the fixes and copying changes to my forked repo (because I don't know how to go to the targeted tag in my forked repo) so I can't really self-test the changes on my forked repo.

**Comment by souravjain540** [comment]
@yuval-hazaz @tupe12334 can you help here.

**Comment by yuval-hazaz** [comment]
Thanks @evansnguyen 

we will review soon

**Review by yuval-hazaz — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
@evansnguyen thanks for your contribution, great work.

**Pull request merged**
