### PR TITLE
Added default usr/pwd as per issue #6200

### PR DESCRIPTION
**Pull request by professorabhay**
Close: #6200 

## PR Details

As per the requirement, modified the readme files and added default usr/pwd

### Summary
📝🐛🚀

This pull request updates the README files of `amplication-client`, `amplication-server`, and `amplication-build-manager` to document the default user credentials for the app. This helps users to access the app more easily in development and production modes.

> _Sing, O Muse, of the skillful developers who wrought_
> _The mighty app of Amplication, with wisdom and thought._
> _They added a note to the README files, both client and server,_
> _To guide the curious users who wish to test their endeavor._

### Walkthrough
*  Add a note about the default user credentials for the app in production mode to the README files of `amplication-build-manager`, `amplication-client`, and `amplication-server` ([link](https://github.com/amplication/amplication/pull/6308/files?diff=unified&w=0#diff-9f9aba2b3f74f5ccd876b9c744ac948aa8f5f91df1ecede030e6402347a91c74R47), [link](https://github.com/amplication/amplication/pull/6308/files?diff=unified&w=0#diff-1e947609f749c026b20d1884e8e500bd55073227c4e02ce2b5fe47711a51d3c2L22-R22), [link](https://github.com/amplication/amplication/pull/6308/files?diff=unified&w=0#diff-905c807d3225fee10e0b8e80b2ab041b6865ddd813fae12c02048ed8e004bf15L19-R19))
* Remove redundant line breaks in the `Learn More` section of the `amplication-client` README and the `Optional: Google Cloud Platform` section of the `amplication-server` README ([link](https://github.com/amplication/amplication/pull/6308/files?diff=unified&w=0#diff-1e947609f749c026b20d1884e8e500bd55073227c4e02ce2b5fe47711a51d3c2L65-R65), [link](https://github.com/amplication/amplication/pull/6308/files?diff=unified&w=0#diff-905c807d3225fee10e0b8e80b2ab041b6865ddd813fae12c02048ed8e004bf15L90-R90))

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by professorabhay** [comment]
Hey @mulygottlieb and @souravjain540, I tried to add default usr/pwd in the Readme files as per the issue #6200. 
Kindly take a look and let me know if you want any modifications. 
Thankyou 🙂

**Comment by mulygottlieb** [comment]
@professorabhay - Thanks for your contribution to Amplication!
Unfortunately, your PR is not what we meant here. You changed the readme files of Amplication services, while the issue talks about changing the README file of the **generated services** (the code the Amplication generates).
Please revert those changes and instead try to take a look at `packages/data-service-generator/src/admin/static/README.md` and packages/data-service-generator/src/server/static/README.md` 😉
Good luck!

**Comment by professorabhay** [comment]
Hey @mulygottlieb, Where would you like to have default usr/pwd.
I tried by adding here - 

``packages/data-service-generator/src/admin/static/README.md`` ->

image

``packages/data-service-generator/src/server/static/README.md`` ->
image

**Comment by mulygottlieb** [comment]
@professorabhay, did you intentionally close your PR? Because you were pretty much on track to finish it :)
All that was missing was to make the change also to the `/server/static/README.md` file (you handled the `/admin/static/README.md` already), and to revert your changes (whitespace only but still) on the other two files in this PR. Please let us know if you want to complete this or prefer we assign it forward. Thanks!

**Comment by professorabhay** [comment]
Hey @mulygottlieb, No, I'll make all the changes and open that PR again. 
Is that changes as shown in above Screenshot works fine ??

**Comment by professorabhay** [comment]
Let me know and then asap I complete that !! 
@mulygottlieb 🙂

**Comment by professorabhay** [comment]
Sure @mulygottlieb, I'll comit all the changes till tomorrow. 
Thankyou ✨

**Pull request closed without merging**
