### PR TITLE
bug(#3895):fixed the button alignment and ui as per the design

### LINKED ISSUE #3895: 🐛 Bug Report: Not align with style button in new project modal
The button in the create new project modal is not aligning with the design spec by @alexbass86 

# The wanted design
New Project

# The existing design
https://user-images.githubusercontent.com/61761153/190987201-c32826c8-e59b-4f64-857f-720b09f7bb88.mov

### PR DESCRIPTION
**Pull request by KlausMikhaelson**
Close #3895 

## PR Details
Fixed the alignment and Ui as per the design

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by souravjain540** [comment]
@abrl91  please review

**Comment by abrl91** [comment]
@KlausMikhaelson 
There are many changes in too many `package-lock.json` files, and I see no reason for that. Is there any chance that you can revert them?

**Comment by KlausMikhaelson** [comment]
@abrl91 Hey I just updated my fork and than git cloned don't know why this happened, I tried redoing everything twice, but will see if I can revert it

**Comment by KlausMikhaelson** [comment]
Hey @abrl91 can you review it again please?

**Comment by abrl91** [comment]
@KlausMikhaelson there are still a lot of `package-lock.json`
Do your branch synced with the latest changes? Did you run something? `npm install`? `bootstrap`?
Something looks very odd.
Can you checkout to your forked master, pull the changes from the remote, check out again to a new bugfix branch, fix the problem, and create a new pull request?

**Comment by KlausMikhaelson** [comment]
yeah I did synced them and entered npm i and than npm run setup:dev 
yeah that should work will do that and create a pr again !
Thank you !

**Comment by KlausMikhaelson** [comment]
Hey @abrl91 I have created another pr by following the instructions can you please review it ? https://github.com/amplication/amplication/pull/4267

**Pull request closed without merging**
