### PR TITLE
Change Kafka broker IDs to match the new MSK Cluster

### PR DESCRIPTION
**Pull request by shaharblanksela**
The msk-cluster changed, therefor the brokers changed as well and need to be changed.
For staging, it's a fix to correct OAuth.

### CODE REVIEW

**Comment by arielweinberger** [comment]
Please add a description. Why should the broker IDs change and what is the outcome?

**Comment by shaharblanksela** [comment]
> 

The production deployed different msk - cluster there for the brokers changed as well.

**Comment by arielweinberger** [comment]
Please include this information in the description and title of the issue.

**Comment by arielweinberger** [comment]
Thanks, I've updated the title to `Change broker IDs to match the new MSK Cluster`

**Pull request merged**
