### PR TITLE
feat(server): add user object to request for REST endpoints

### PR DESCRIPTION
**Pull request by narayand16**
This is WIP PR for issue #1723

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@narayand16 let us know if you need support from the team to complete this PR

**Comment by narayand16** [comment]
> @narayand16 let us know if you need support from the team to complete this PR

Yes @yuval-hazaz I do need some assistance in completing this PR. I tried to connect with @tupe12334 , but that didn't happened yet.

**Comment by mshidlov** [comment]
@tupe12334 please update on the PR status

**Comment by tupe12334** [comment]
resolve this issue in #2041

**Pull request closed without merging**
