### PR TITLE
Feat/2593 logger

### PR DESCRIPTION
**Pull request by tupe12334**
fix: #2593 

## PR Details

This pr remove the loggin from individual services and make a shared lib called @amplication/logger
## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by abrl91** [comment]
> @abrl91 Shall we close this PR and re-open it at a later point in time? It's too old, with so many changes, and a lot of conflicts already.

I think you should ask Ofek. He worked on that

**Comment by arielweinberger** [comment]
Oops, tagged the wrong person. @tupe12334 What do you think?

**Comment by tupe12334** [comment]
> Oops, tagged the wrong person. @tupe12334 What do you think?

Not really I think that we can merge it to next release, but the question is if the product wants

**Comment by yuval-hazaz** [comment]
@arielweinberger @tupe12334 your call

**Comment by arielweinberger** [comment]
@yuval-hazaz I'd like to spend a while reviewing this to make sure we do proper logging. Will do today.

**Comment by arielweinberger** [comment]
@tupe12334 As discussed, let's close this one and tackle it separately. I've created an issue: https://github.com/amplication/amplication/issues/3209

I'd like to do this in two separate steps:
1. A PR to introduce the `@amplication/logger-module` library
2. Implementing the library in our microservices. This can happen at once or gradually, and we will discuss this as a team to decide.

**Pull request closed without merging**
