### PR TITLE
refactor(client): updated tooltips

### PR DESCRIPTION
**Pull request by p1kalys**
Close: #8806

## PR Details

Refactored the tooltips to avoid talking about node.js only 

## PR Checklist

- [✅] Tests for the changes have been added
- [✅] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by PazYanoverr** [comment]
Hi @p1kalys,
Reviewed it, and it LGTM.
@morhag90 - Can you please review and push to next? (@mulygottlieb - FYI)

**Comment by p1kalys** [comment]
Hi Team, any update on this PR?

**Comment by PazYanoverr** [comment]
@mulygottlieb @morhag90 - Can you assist please?

**Review by mulygottlieb — APPROVED** [review]

**Comment by mulygottlieb** [comment]
Thanks for your contribution @p1kalys !
Approved and merged!

**Pull request merged**
