### PR TITLE
Fix/2423 info popup state always open

### PR DESCRIPTION
**Pull request by salindae25**
Issue Number: #2423 

## PR Details

1. Remove `open={supportMenuOpen}` from the Popover element. ( this will allow it to have default behavior)
2.  Added  `onOpen={handleSupportClick}` to the Popover element. ( this will make sure to fire the trackEvent)
3. Removed all `supportMenuOpen`  state related references. 

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by yuval-hazaz — DISMISSED** [review]
@salindae25 congrats for your first contribution with Amplication
Great work

**Comment by muhsinkamil** [comment]
@salindae25 Can we remove onClick at MenuItem on line 110

**Comment by salindae25** [comment]
> @salindae25 Can we remove onClick at MenuItem on line 110

yes, it does not affect the functionality of the popover menu.

**Comment by muhsinkamil** [comment]
> yes, it does not affect the functionality of the popover menu.

@salindae25 
I see, can you please remove that.

The reason is, `trackEvent` is fired twice when the icon is clicked.
First `onOpen`     -> opens tooltip and fires `trackEvent`
second `onClick` -> does nothing ( since open already ) and fires `trackEvent`

cc: @yuval-hazaz

**Comment by salindae25** [comment]
> > yes, it does not affect the functionality of the popover menu.
> 
> @salindae25 I see, can you please remove that.
> 
> The reason is, `trackEvent` is fired twice when the icon is clicked. First `onOpen` -> opens tooltip and fires `trackEvent` second `onClick` -> does nothing ( since open already ) and fires `trackEvent`
> 
> cc: @yuval-hazaz

sure i'll remove click event

**Review by tupe12334 — APPROVED** [review]

**Pull request merged**
