### PR TITLE
fix: updated incorrect last sync date

### LINKED ISSUE #3585: 🐛 Bug Report: Last sync value is incorrect
### What happened?

When you sync to GitHub and look at the Last sync value in the client, it's not right.

Screen Shot 2022-08-25 at 10 57 49

This happened before the first build
### What you expected to happen

Show the correct time

### How to reproduce

Generate a resource and connect to GitHub

### Amplication version

0.15.0

### Environment

_No response_

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TheLearneer**
Fixes #3585 

## PR Details
Fixed the last sync date showing up incorrect value.
This was especially in the case when syncing was never done in the first place.

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

### CODE REVIEW

**Comment by arielweinberger** [comment]
@abrl91 Would you like to take a look at this?

**Comment by abrl91** [comment]
create branch

**Comment by TheLearneer** [comment]
> create branch

run branch ??

**Comment by abrl91** [comment]
> > create branch
> 
> run branch ??

LOL yes. Never mind, I copied your changes and tested them. Looks great!

**Pull request merged**
