### PR TITLE
feat: added devcontainer config file for github codespaces and remote dev environments

### PR DESCRIPTION
**Pull request by endalk200**
Close: #5826 

## PR Details

This PR is linked to this GitHub issue [#5826](https://github.com/amplication/amplication/issues/5826). Adds GitHub codespaces and remote devcontainer support to amplication repository

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by souravjain540** [comment]
@levivannoort  any updates on this?

**Comment by levivannoort** [comment]
Hey @endalk200, first of all thanks for the contribution. I think this could be very beneficial for a lot of first time contributers aswell. I have a few discussion points from diving into devcontainers a bit more.

1. I think we would want to introduce a README.md file in the .devcontainer directory aswell on how to use the file, where we could link to some github documentation on using it in codespaces.

2. For the portsAttribures, I would say that we could drop the following; 'kafka-ui', 'storybook', 'git-pull-service' and 'git-push-webhook-service' (as these last two are currently not used in the production environment. And we could add the 'git-pull-request-service' since that is used but not present in the configuration.

3. I forked the current 'master' branch and added the setup to the fork and tried to use it in the codespaces, but on my end it didn't seem like the postCreateCommand was actually doing anything - i.e., installing dependency, et cetera.

4. In the issue you mention you want to 'run amplication' on github codespaces, but should we than also actually run the different services and other dependencies - e.g., kafka, postgresql. This also raises the question on whether we would want to include the docker-compose in the configuration and maybe 'serve' the components by running them via the Dockerfile aswell. And if we're going to be running the services we should probably also use the option to forwardPorts.

I think not all of the discussion points are on you, but would love to hear your opinion. Would could also look into making it work on vscode aswell.

**Comment by endalk200** [comment]
> 

1. Sure. I can add a readme file into the devcontainer directory.
2. The port attribute field should include all edge cases where those services might be run. All services ports that I can run in the repo should be added but I can remove those you mentioned. Do you want me to remove it or?
3. I have tested it before I pushed but I'll check it out.
4. I think we should about that. Currently we don't have a dockerfile that supports hot reload if we have that we can add a docker compose file inside the devcontainers repo. If we do that it will also support remote container development in local vscode. When you open a repo with devcontainers directory vscode will ask you if you want to open it.

**Comment by endalk200** [comment]
@levivannoort can you confirm on #2?

**Comment by levivannoort** [comment]
Very quick response! Regarding number two i'd say you're right and atleast for now we could probably keep the services in even though they're not used. Might want to als add assignments for kafka [9092]- since we're specifying kafka-ui, postgresql [5432].

**Comment by levivannoort** [comment]
Regarding the additional docker-compose on the devcontainer directory with the symlink to the other dockerfiles and building in a hotreload option, that is a great idea. Could also be done from a seperate issue and see this as a minimal-viable-product.

Just as a heads-up I created a pull request for the dockerfiles a  while ago but it hasnt been merged yet, but we can look at incorporating a hot-reload mechanism on top of that.

**Comment by endalk200** [comment]
> Regarding the additional docker-compose on the devcontainer directory with the symlink to the other dockerfiles and building in a hotreload option, that is a great idea. Could also be done from a seperate issue and see this as a minimal-viable-product.
> 
> Just as a heads-up I created a pull request for the dockerfiles a while ago but it hasnt been merged yet, but we can look at incorporating a hot-reload mechanism on top of that.

I think this excellent idea. We want to make sure our dev environment and deployment environment is as close as possible to mitigate environment setup issues.

**Comment by endalk200** [comment]
> 

We are not going to consume postgres and kafka from the browser and I think we don't need to expose those ports.

**Comment by endalk200** [comment]
> Very quick response! Regarding number two i'd say you're right and atleast for now we could probably keep the services in even though they're not used. Might want to als add assignments for kafka [9092]- since we're specifying kafka-ui, postgresql [5432].

@levivannoort I have pushed a new commit with those new ports.

**Comment by levivannoort** [comment]
> > Regarding the additional docker-compose on the devcontainer directory with the symlink to the other dockerfiles and building in a hotreload option, that is a great idea. Could also be done from a seperate issue and see this as a minimal-viable-product.
> > Just as a heads-up I created a pull request for the dockerfiles a while ago but it hasnt been merged yet, but we can look at incorporating a hot-reload mechanism on top of that.
> 
> I think this excellent idea. We want to make sure our dev environment and deployment environment is as close as possible to mitigate environment setup issues. Is there a blocker or WIP for this PR #5065

There was a blocker regarding some infrastructure work and some auditing working. Those have been taken care of and ill try to get those out of the door at the end of next week.

**Comment by endalk200** [comment]
> 

Not yet. Let me quickly do that.

**Comment by endalk200** [comment]
@levivannoort I have fixed the issue where the postCreateCommand wasn't running. Also changed the labels to lowercase. The documentation says the `postCreateCommand` is of type string, array or object but it didn't work with the array. I have reported the issue. This PR should be ready now.

**Comment by levivannoort** [comment]
@endalk200 I also added a note about the new addition of codespaces to the refactor of the readme: https://github.com/amplication/amplication/pull/5929/commits/b9a4e2e6a311f4ace8e60b5871c796476394ef23

Thanks again ❤️

**Pull request merged**
