### PR TITLE
fix(client): center align delete project text in project settings

### PR DESCRIPTION
**Pull request by sanskar-soni-9**
Close: #7177

## PR Details

Center aligned text for delete project button on project settings page.

amplication

### Summary
📐📱🖊️

Improve the layout and usability of the project form page by using design system utilities. Add a new prop to `FlexItem` to control the alignment of its children.

> _Sing, O Muse, of the skillful coder who refined_
> _The project form page with `EnumItemsAlign`,_
> _And made it fit for every screen and device,_
> _As graceful as the work of Hephaestus divine._

### Walkthrough
*  Import `EnumItemsAlign` enum to use for flex item alignment ([link](https://github.com/amplication/amplication/pull/7191/files?diff=unified&w=0#diff-02e6a440827a1ae5bc4371de6c9e0223b694b696995593041432cdc3b267c8b6R3))
*  Add `itemsAlign` prop to `FlexItem` component to center project name and description fields ([link](https://github.com/amplication/amplication/pull/7191/files?diff=unified&w=0#diff-02e6a440827a1ae5bc4371de6c9e0223b694b696995593041432cdc3b267c8b6L25-R26))
*  Improve layout and responsiveness of `ProjectFormPage` component ([link](https://github.com/amplication/amplication/pull/7191/files?diff=unified&w=0#diff-02e6a440827a1ae5bc4371de6c9e0223b694b696995593041432cdc3b267c8b6R3),[link](https://github.com/amplication/amplication/pull/7191/files?diff=unified&w=0#diff-02e6a440827a1ae5bc4371de6c9e0223b694b696995593041432cdc3b267c8b6L25-R26))

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

### CODE REVIEW

**Comment by souravjain540** [comment]
hello, we will wait till tomorrow if the original assignee didn't make a PR then we will accept otherwise we have to close your pr.

meanwhile please leave a comment on the issue.

**Review by barshimi — APPROVED** [review]

**Comment by sanskar-soni-9** [comment]
@souravjain540 Thank you. I should have had it assigned to me before working on it. Next time, I will definitely follow the proper procedure. 🙂

**Comment by souravjain540** [comment]
please leave a comment on issue @sanskar-soni-9

**Comment by sanskar-soni-9** [comment]
Done. @souravjain540

**Pull request merged**
