### PR TITLE
Improve log entries library with additional information

### PR DESCRIPTION
**Pull request by gitstart**
Fixes https://github.com/amplication/amplication/issues/5974

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by overbit** [comment]
@gitstart  Thanks for the contribution, although, in order to solve the issue, we also need the rest of the requirements to be satisfied

**Comment by olalekanteeblaze** [comment]
@overbit I need some clarifications on what we need to do to satisfy the remaining requirements

**Comment by overbit** [comment]
> @overbit I need some clarifications on what we need to do to satisfy the remaining requirements

We'd like to automatically add the caller function and class names to simplify debugging

**Comment by olalekanteeblaze** [comment]
@overbit what do we need to achieve this. Are we adding more params?

**Review by overbit — APPROVED** [review]

**Comment by overbit** [comment]
@gitstart @olalekanteeblaze the tests are not passing meaning that there are still some old calls to the old parameters.
Can you please fix it?

**Review by overbit — APPROVED** [review]

**Pull request merged**
