### PR TITLE
Added default usr/pwd

### PR DESCRIPTION
**Pull request by professorabhay**
Close: #6200 

## PR Details

added default user/pwd in readme files as said - 
1 - packages/data-service-generator/src/admin/static/README.md
2 - packages/data-service-generator/src/server/static/README.md

### Summary
:memo::lock::pencil2:

This pull request updates the README.md files in the `packages/data-service-generator/src/admin/static` and `packages/data-service-generator/src/server/static` directories to provide the user with the default user credentials for the admin and server components of the data service generator.

> _We are the data service generator_
> _We create the admin and server_
> _We document our default user_
> _`admin` is the password and username_

### Walkthrough
*  Add comment about pre-configured user for admin component ([link](https://github.com/amplication/amplication/pull/6360/files?diff=unified&w=0#diff-5d02187512f2f428985b65d42ed17ad1bbe7cf5f4fbd57acfdb09726978adcadL41-R41))
*  Add sentence about pre-configured user for server component ([link](https://github.com/amplication/amplication/pull/6360/files?diff=unified&w=0#diff-63cbd32e0efaa40dd2fb7555004b89899226b26dd7d387d7e6e97c45c0a9ec1fR60))
*  Fix typo in `npm run eject` command for admin component ([link](https://github.com/amplication/amplication/pull/6360/files?diff=unified&w=0#diff-5d02187512f2f428985b65d42ed17ad1bbe7cf5f4fbd57acfdb09726978adcadL53-R53))

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by professorabhay** [comment]
Hey @mulygottlieb and @souravjain540, Kindly review the changes I make ad per issue #6200.

**Review by yuval-hazaz — APPROVED** [review]
I approve the changes, but the CI will not pass until you update the snapshot file

**Comment by yuval-hazaz** [comment]
@overbit @levivannoort @mulygottlieb This PR does not trigger the CI since it only includes changes in README files but since these files impact the DSG and the snapshot, we should consider removing the condition on the workflow

it makes sense to skip the CI when we only change the project README so we can keep the condition if we will be more specific but it may also make sense to drop the condition completely

**Comment by yuval-hazaz** [comment]
@professorabhay to update the snapshot with your changes run this command 
```
npx nx run data-service-generator:update-snapshot
```

**Review by overbit — APPROVED** [review]

**Comment by professorabhay** [comment]
hey @yuval-hazaz, 
image

**Pull request merged**
