### PR TITLE
fix(server): Use passive text for UI Texts

### PR DESCRIPTION
**Pull request by SergeWilfried**
Issue Number: #3456

## PR Details

Passive text is not recommended in UI texts (or documentation) if it can be avoided.

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by MoFoGo — APPROVED** [review]
Approve merge.

**Comment by arielweinberger** [comment]
Hey @SergeWilfried - I've changed the base branch to 0.15.0 where we currently are making some decent refactoring to the UI.

The file in which you made the change is available at `packages/amplication-client/src/Resource/ApplicationAuthSettingForm.tsx`. Can you please fix the PR (or create a new one, where the base branch is `release/0.15.0`)?

Sorry for the inconvenience and thanks for your contribution!

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]
@SergeWilfried  please remove the additional file `.dccache` from the PR and I will approve and merge it

**Comment by yuval-hazaz** [comment]
Sorry, I just saw the comments from @arielweinberger please ignore my comments and follow the instructions by Ariel to proceed

**Comment by SergeWilfried** [comment]
Hey @arielweinberger just reopened the PR [here](https://github.com/amplication/amplication/pull/3533). Closing this

**Pull request closed without merging**
