### PR TITLE
Create My_Amplication_Blog_post.md

### LINKED ISSUE #4006: Advocacy: Write a blog post about Amplication
We always promote non and low-code contributions to Amplication.

In this issue you have to write a blog post or article about the experience of using Amplication or make a tutorial that about any project using Amplication.

**The blog must include unique content based on your experience and not just a copy-paste from other blogs or Amplication web site.** 

This article should be published on any platform of your choice(for example, Medium, Dev. to, Hashnode, etc.).

You have to create a PR by making a new file(in which there is link to that article) in `tutorials` folder.

This contribution will count as **Two contributions** to the Amplication Hacktoberfest campaign.

### PR DESCRIPTION
**Pull request by Abubakrce19**
resolved #4006 

Close #[issue-number]

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by Abubakrce19** [comment]
#4006

**Comment by Abubakrce19** [comment]
@souravjain540 
@abrl91 
Review please thank you

**Review by souravjain540 — CHANGES_REQUESTED** [review]
please exchange the screenshots with new one and please add more content

**Comment by csgochan** [comment]
> please exchange the screenshots with new one and please add more content

Roger

**Comment by Abubakrce19** [comment]
> please exchange the screenshots with new one and please add more content

0- Screenshots are exchanged.
1- Added My experience working with Amplication.
2- Added more detailed steps to create your first application.
3-Added an extra Final paragraph.
Thank you!!
@souravjain540

**Review by souravjain540 — APPROVED** [review]

**Comment by abrl91** [comment]
@Abubakrce19 why did you close the PR?

**Comment by Abubakrce19** [comment]
@abrl91 I am really really sorry 
I accidentally deleted

**Comment by Abubakrce19** [comment]
My 2nd re-review 🤦‍♂️
(yes I am giving headache to Saurav Jain)

**Comment by abrl91** [comment]
@souravjain540 Can you review it, please?

**Comment by Abubakrce19** [comment]
> @souravjain540 Can you review it, please?

Already approved 1 time earlier.
Thanks

**Comment by arielweinberger** [comment]
@Abubakrce19 Please be patient. Thank you.

**Pull request merged**
