### PR TITLE
Merge/4055

### PR DESCRIPTION
**Pull request by barshimi**
Close: #3396

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by barshimi** [comment]
community PR.
@arielweinberger this PR fail to load @amplication/nest-logger-module inside @amplication-git-service, because it is  a library and not package (it doesn't have dockerfile).
Please check this issue again to insure it's valid and possible.

**Comment by GreenMachine01** [comment]
@overbit @arielweinberger please review.

**Comment by yuval-hazaz** [comment]
I am closing this PR due to inactivity
Please reopen if it still needed

**Comment by overbit** [comment]
@yuval-hazaz I actually fix the conflicts yesterday, I'll reopen it.

**Review by yuval-hazaz — APPROVED** [review]

**Comment by EugeneTseitlin** [comment]
@overbit please, don't forget to link PR to the issue

**Pull request merged**
