### PR TITLE
Update NewProject.tsx

### PR DESCRIPTION
**Pull request by Martande8055**
issue #3956 

transitionDuration is added in amplication/packages/amplication-client/src/Project/NewProject.tsx

### CODE REVIEW

**Comment by arielweinberger** [comment]
Thanks @Martande8055 

Can you please set a proper title and description, so it's clear what this PR is about (ideally without having to enter the issue)?

@alexbass86 Currently the PR sets the appearance transition of the error box to one second. This seems a bit too slow to me. What do you think? How much should it be?

**Comment by arielweinberger** [comment]
Hi @Martande8055 thanks for your PR.

We actually noticed that this entire screen is not in sync with how we handle errors at Amplication. Will you be able to adjust your PR to match with our design system? For example, like this:

image

Note that the spacing between the field and the error message is 4px.

**Review by arielweinberger — CHANGES_REQUESTED** [review]
Hi @Martande8055 thanks for your PR.

We actually noticed that this entire screen is not in sync with how we handle errors at Amplication. Will you be able to adjust your PR to match with our design system? For example, like this:

image

Note that the spacing between the field and the error message is 4px.

**Comment by arielweinberger** [comment]
Refer to this issue:
https://github.com/amplication/amplication/issues/4015

**Comment by abrl91** [comment]
run branch

**Comment by abrl91** [comment]
run branch

**Comment by abrl91** [comment]
@Martande8055 can you respond to Ariel's review?

**Comment by Martande8055** [comment]
sorry, I'm currently a little bit busy. can you assign this issue to someone else?

**Pull request closed without merging**
