### PR TITLE
fix(amplication-client): fixed a typo in OverviewTile Next JS => Nest JS

### PR DESCRIPTION
**Pull request by regisBafutwabo**
Issue Number: #3424

## PR Details

I fixed a typo that was in the dashboard (#3424 )

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by yuval-hazaz — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
Thanks for your first contribution @regisBafutwabo  🚀

**Review by yuval-hazaz — APPROVED** [review]

**Comment by arielweinberger** [comment]
@regisBafutwabo Can you please see if you can fix the conflicts? Then I can merge your PR :)

**Comment by regisBafutwabo** [comment]
Of course let me check it!

**Comment by regisBafutwabo** [comment]
> @regisBafutwabo Can you please see if you can fix the conflicts? Then I can merge your PR :)

I can't really see where the conflict happened and `implication:release/0.15.0` can't be checked out. Maybe I'm doing something wrong

**Comment by arielweinberger** [comment]
I think that in `0.15.0` the `OverviewTile.tsx` file has moved:
```amplication/amplication/packages/amplication-client/src/Resource/OverviewTile/OverviewTile.tsx```

Would you like to re-implement this change? Feel free to do it in this PR or in a new PR. Make sure that the `release/0.15.0` is your base branch. Apologies for the inconvenience.

**Comment by regisBafutwabo** [comment]
> I think that in `0.15.0` (currently in development), the `OverviewTile.tsx` file has moved: `amplication/amplication/packages/amplication-client/src/Resource/OverviewTile/OverviewTile.tsx`
> 
> And the `version.ts` file change for `data-service-generator` isn't needed anymore, it's been updated already.
> 
> Would you like to re-implement this change? Feel free to do it in this PR or in a new PR. Make sure that `release/0.15.0` is your base branch. Apologies for the inconvenience.

it's all good I will just create a new PR from 0.15.0 it's way easier

**Pull request closed without merging**
