### PR TITLE
Update .prettierrc

### PR DESCRIPTION
**Pull request by Aditya-Kapadiya**
Hello,
I have changed the link that had HTTP to HTTPS.

Thank You

Close: #[issue-number]

### Summary
🔒🌐🆙

Updated the schema URL in `.prettierrc` to use HTTPS for security reasons.

> _`schema` now secure_
> _HTTPS replaces HTTP_
> _a winter upgrade_

### Walkthrough
* Update the schema URL to use HTTPS for security ([link](https://github.com/amplication/amplication/pull/7213/files?diff=unified&w=0#diff-663ade211b3a1552162de21c4031fcd16be99407aae5ceecbb491a2efc43d5d2L2-R2))

## PR Checklist

- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by overbit — CHANGES_REQUESTED** [review]
@Aditya-Kapadiya Thanks for the contribution but you would need to follow the PR template instructions / [CONTRIBUTING](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md) guidelines

It's missing the issue and the PR is not properly formatted as per PR template guidelines

**Comment by Aditya-Kapadiya** [comment]
@overbit Hello, can you please guide me to solve the mistake done by me?

**Comment by levivannoort** [comment]
@Aditya-Kapadiya please create an issue first, this can be a Bug Report - the template for the issue will guide you on the information to provide.

**Comment by mulygottlieb** [comment]
Closing this PR since it is not connected to any issue and there is no response to our comments on the PR

**Pull request closed without merging**
