### PR TITLE
Client - 404/Not Found Page

### PR DESCRIPTION
**Pull request by goingdust**
Close: #4601 

## PR Details

Created a 404 page for the client by adding a "*" route that catches any undefined routes and then renders the NotFoundPage component.

Screenshot from 2022-12-14 17-55-52

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@alexbass86 @GreenMachine01 please review and provide an updated design for the page
@barshimi please review the routing config

**Review by alexbass86 — CHANGES_REQUESTED** [review]
This page isn't with our visual language. We need to design it and ensure it's aligned with other pages. @GreenMachine01

**Review by barshimi — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
@GreenMachine01 please open an issue for @alexbass86 to prepare a new design for the page

**Comment by yuval-hazaz** [comment]
@goingdust thanks for your first contribution with us, we appreciate it 💜

**Pull request merged**
