### PR TITLE
Update NewWorkspace.tsx

### PR DESCRIPTION
**Pull request by Himanxu1**
improve

Issue Number: #3657 

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]
@Himanxu1 this fix makes sense but it will not resolve the issue that talks about the text field

**Comment by Himanxu1** [comment]
@yuval-hazaz  okay . How can I do that ?

**Comment by yuval-hazaz** [comment]
> @yuval-hazaz okay . How can I do that ?

Usually the error display is resolved by adding ValidateOnBlur but I see it is already there. Can you please test if you can reproduce the error or maybe it is resolved already?

**Review by tupe12334 — APPROVED** [review]

**Comment by tupe12334** [comment]
I approved the code until this point but still don't fix the issue

**Comment by Himanxu1** [comment]
Hey @tupe12334  I am unable to check the result of my code because i haven't set up the amplication locally and this issue is solved only when i have set up locally and check the result

**Comment by yuval-hazaz** [comment]
@tupe12334 what do we need in order to move forward with this PR?

**Comment by yuval-hazaz** [comment]
I am closing this PR since the issue was already resolved in another PR
Thanks for your contribution @Himanxu1 
I hope you will get your env up and running soon and will be able to contribute more to the project.

**Pull request closed without merging**
