### PR TITLE
fix GitHub account menu design

### PR DESCRIPTION
**Pull request by jainpawan21**
Issue Number: #2413 

## PR Details

1. Added border-radius: 50% to GitHub avatar image
2. Added CSS for selected icon position
3. Used react component in menu title button instead of the string value

https://user-images.githubusercontent.com/39362422/160859022-5d9c50ef-83e9-4243-8bc9-46c89903d0c4.mov

## PR Checklist
- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by mshidlov** [comment]
@jainpawan21 thank you for submitting this PR

**Comment by tupe12334** [comment]
@jainpawan21 Please update the packages/amplication-client/src/Application/git/GitActions/ExistingConnectionsMenu.scss file and change the git-organization-select-menu  __hr back ground color to be --black2 to make its look good in light mood

**Comment by tupe12334** [comment]
@jainpawan21 And update the description text to be var(--black) so that the text will update his color to be visible.

**Comment by tupe12334** [comment]
@yuval-hazaz I saw you approved the changes, can you please check my reviews? I think this pr don't ready yet.

**Comment by tupe12334** [comment]
@jainpawan21 Are you want to fix the rejects or merge that and we will open an issue to fix them?
@yuval-hazaz any input?

**Comment by jainpawan21** [comment]
> @jainpawan21 Are you want to fix the rejects or merge that and we will open an issue to fix them? @yuval-hazaz any input?

I am just fixing the rejects. Give me a few minutes.

**Comment by jainpawan21** [comment]
> @jainpawan21 And update the description text to be var(--black) so that the text will update his color to be visible.

Hi @tupe12334 , What do you mean by **description text** ?

**Comment by tupe12334** [comment]
@jainpawan21 You can see that there is a text below the title that its color is white, but when the background is because white the text don't switch to black

**Comment by jainpawan21** [comment]
@tupe12334, Please review again, I just fixed defects

**Review by tupe12334 — APPROVED** [review]

**Comment by tupe12334** [comment]
@jainpawan21 You did a great job!
@mshidlov approved by me and @yuval-hazaz, can you merge or I will merge?

**Comment by souravjain540** [comment]
> @tupe12334, Please review again, I just fixed defects

You're the best, Pawan!

Thanks for another PR :)

**Pull request merged**
