### PR TITLE
fix(client): github sync toggled-off unconfirm

### LINKED ISSUE #1196: Client: Unconfirmed github sync toggle-off won't return to checked state.
**Describe the bug**
A 'Sync with Github' switch button, if being toggled off but cancelled, won't return back to it's visually 'checked' state (unless a page refresh is triggered).

**To Reproduce**
1. Go to an app's 'Sync with Github' setting panel, make sure its already set to synced.
2. Try toggle off the switch, it temporarily get visually 'unchecked'. Meanwhile you get promped by a confirm dialog.
3. Clicked dismiss /  close / click outside the dialog.
4. The toggle won't return 'checked', only visually, because click it will promp comfirm again.
5. Refresh the app. The toggle goes back to normal.

**Expected behavior**
The switch button should switch back to the 'checked' state once the user cancelled the toggle-off.

**Screenshots**
uncancellable-toggle-off
_The bug_

Grabación de pantalla 2021-02-03 a las 12 45 56 a  m
_The ideal behavior_

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2 (20D64)
 - Browser: Microsoft Edge
 - Version: 88.0.705.56

**Additional context**
- Was trying to look into #1127, but found this issue instead.

### PR DESCRIPTION
**Pull request by liyachun01**
Fix #1196.

When a toggle-off is clicked, the `Toggle` component triggers an `onValueChange` and behind the scenes, an implicit `[MDCSwitchFoundation].setChecked(false)` was fired .

Now that the toggle-off is cancelled, the app must explicitly call `[MDCSwitchFoundation].setChecked(true)` in order to get back to its 'checked' state.

Grabación de pantalla 2021-02-03 a las 1 06 28 a  m

### CODE REVIEW

**Comment by liyachun01** [comment]
1. Some unintentional modification to the `package.lock.json` files was included.
2. Some generated `models.ts` files was included.

May bother your help to remove them.

**Comment by yuval-hazaz** [comment]
Well done, thanks.
I will take care of the extra changes files.
Congrats on your first PR.

**Comment by liyachun01** [comment]
> Well done, thanks.
> I will take care of the extra changes files.
> Congrats on your first PR. 

Yay!

**Comment by yuval-hazaz** [comment]
@all-contributors please add @liyachun01  for code

**Pull request merged**
