### PR TITLE
fix(data-service-generator): wrong args for generated `count` action

### PR DESCRIPTION
**Pull request by ognjenjevremovic**
Close: #6056 

## PR Details

Change the generated code for `ServiceBase` class, to match the valid types for the `count` operation for argument type.  
Update `jest` testing-snapshots to match the code change.

### Summary
🆕🔄🛠️

This pull request updates the data service generator to use the new `COUNT_ARGS` type for the `count` method of the service classes, following the changes in the Prisma client. It also modifies the template files `create-service.ts` and `service.base.template.ts` to reflect this change.

> _`COUNT_ARGS` added_
> _Template mapping changes_
> _Fall of `FIND_MANY`_

### Walkthrough
*  Add a new type identifier `COUNT_ARGS` to the template mapping object for generating service classes ([link](https://github.com/amplication/amplication/pull/6082/files?diff=unified&w=0#diff-9af0fb5e24fec67389a8d46017a442d19725496874d46493feb14029f48ce657R304))
*  Update the base service class to use the `COUNT_ARGS` type for the `count` method and the generic type parameter `T` ([link](https://github.com/amplication/amplication/pull/6082/files?diff=unified&w=0#diff-456f752b8503d5632ca12faeb990b0a26b6389f6edcf71fec1f585cfab3c152bL15-R16))

## PR Checklist

- [ ] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by ognjenjevremovic** [comment]
Hey @yuval-hazaz I think you might be right.  
Testing the changes locally, from the generated code output, I can see the following in the `user.resolver.base.ts` file:

```ts
  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async _usersMeta(
    @graphql.Args() args: UserFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }
```

I want to draw the attention to the type of `args` passed to the `this.service.count` method call.  
`count` method (on the `UserServiceBase` class) is called with the `args` of type `UserFindManyArgs` in the resolver, where the contract from within `user.service.base.ts` on the generated `UserServiceBase` class accepts the args of type `UserCountArgs` as following:

```ts
  async count<T extends Prisma.UserCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserCountArgs>
  ): Promise<number> {
    return this.prisma.user.count(args);
  }
```

Were you referring to this?  
It seems that the `resolver` should be updated as well then?

**Comment by overbit** [comment]
@ognjenjevremovic you are correct. I'd suggest to update the `controller` and `resolver` with a mapping that will translate the input args into the needed args for the `count` method of the `service` class.

**Comment by ognjenjevremovic** [comment]
Hey @overbit I apologise for my slight delay in response.  
I missed your previous comment (it must have flied over my email unnoticed).

I will update the `contoller` and `resolver` templates accordingly. It might take me a day or two, as per busy working week, but I'll try do it asap 🙂.

**Comment by ognjenjevremovic** [comment]
Hey @overbit I've updated the `resolver` argument data mapping to match the expected type for the `count` method on the service class instance.  
The changed required introducing a new `code-gen-type` (or at least, that was my understanding of it), for specifying the `countArgs` argument.

I’ve created a new graphql dto for handling the mapping of the incoming data to `COUNT_ARGS` in the `META_QUERY` handler.  
The snapshots have been updated and the new set of test(s) have been supplied for the `create-count-args` utility, for generating the data mapper.

Please do let me know if everything is in order 🙂.

I was wondering if exposing the `count` handler on the controller would be the next step, since the resolver has the `_metaQuery` for getting the count of the documents matching the query? Would that inline with the goals of the project?  
If so, may I open an issue for extending the controller with the `count` handler and submitting the PR (as I was experimenting with extending the controller while working on the resolver part) 🚀 .

Many thanks!

**Comment by mulygottlieb** [comment]
Thanks a lot @ognjenjevremovic !
We will review this soon.

Your suggestion for the controller is a very good one! but this specific task is reserved for other purposes at the moment so please do not submit such a PR right now 😊

**Comment by mulygottlieb** [comment]
BTW @ognjenjevremovic  if you're looking for an interesting challenge, would you like to look at #5877?

**Comment by ognjenjevremovic** [comment]
Hey @mulygottlieb thank you for your prompt feedback 🚀 .

Sure, I'll take a closer look at #5877 🙂.  
I'd quickly just go through the failing tests first and update them accordingly. As I see some tests are failing after the latest changes (even though the snapshots were updated in the last commits).

**Review by overbit — APPROVED** [review]
Nice work @ognjenjevremovic 💯

**Comment by overbit** [comment]
@ognjenjevremovic can you double check the failing test so we can merge? Thanks

**Review by overbit — APPROVED** [review]
💯 !!!

**Pull request merged**
