### PR TITLE
Return the DSG to the tsconfig

### PR DESCRIPTION
**Pull request by tupe12334**
This PR puts the DSG back to the main tsconfig and we open a separate issue to remove it orderly #4994

### CODE REVIEW

**Comment by overbit** [comment]
@tupe12334 what is the reason to add it back here? What are we trying to achieve?

**Comment by tupe12334** [comment]
We removed this to prevent a bug in runtime and we fixed the bug, but now in compile time we use the files in a local test that crash without this https://github.com/amplication/amplication/blob/master/packages/amplication-data-service-generator-runner/scripts/create-input-json.ts

**Comment by EugeneTseitlin** [comment]
@tupe12334 Nether issue nor the code change is obvious for me. Please, link the corresponding issue to this PR. If doesn't exist yet, then create it first and describe a problem there.

**Comment by abrl91** [comment]
@tupe12334 I don't understand why we need to roll back to this approach, in one of your previous PR you changed it and explained to me why. So, why do we need it like that now?

**Comment by overbit** [comment]
This is now overruled by #4943

**Pull request closed without merging**
