### PR TITLE
refactor(client): Removed unused gQL query from WorkspaceLayout

### LINKED ISSUE #2599: 🐛 Bug Report: Unused code in WorkspaceLayout.tsx
### What happened?

The graphql query used in line number 90 is not used anywhere can we please remove it if it is not used anywhere.

### What you expected to happen

Please remove line 90 in the file ` https://github.com/amplication/amplication/blob/master/packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx` if it is not used.

### How to reproduce

Please check `WorkspaceLayout.tsx` in the Project 

### Amplication version

_No response_

### Environment

_No response_

### Are you willing to submit PR?

_No response_

### PR DESCRIPTION
**Pull request by CKanishka**
Issue Number: Fixes #2599 

## PR Details

Removed unused GraphQL query from Workspace Layout page

### CODE REVIEW

**Review by yuval-hazaz — APPROVED** [review]
Thanks for you first PR with us 💜

**Comment by tupe12334** [comment]
@CKanishka Nice job, thanks, hope to see you again in another pr!

**Review by tupe12334 — APPROVED** [review]

**Comment by CKanishka** [comment]
> @CKanishka Nice job, thanks, hope to see you again in another pr!

Sure, looking forward to it.

**Comment by tupe12334** [comment]
@mshidlov Can you merge it or let me know if I can?

**Pull request merged**
