### PR TITLE
#6230  Fixed the service settings not saved issue.

### PR DESCRIPTION
**Pull request by AkhilJ321**
Close: #6230

## PR Details

Fixed the problem of service settings not getting updated on tab change.
This problem was caused during real-time changes, data was not fetched using the Apollo client, so it was showing previously fetched data. I added the refetch functionality. It is working great now.

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by barshimi** [comment]
@AkhilJ321  please move useQuery serviceSettings: models.ServiceSettings; to useResource and expose it to context. then you can use it on all wizard pages and refetch accordingly.

**Review by barshimi — CHANGES_REQUESTED** [review]
@AkhilJ321 look at the comment I wrote at the main conversation page

**Comment by AkhilJ321** [comment]
Thanks for the review.I will try to incorporate them as soon as possible.

**Comment by AkhilJ321** [comment]
@barshimi ,I created the useResource customHook from where now i am performing the query step, but for the expose it to the context part, I am not understanding what to do exactly. I made some changes in appcontextinterface to expose it but then it is disturbing a lot of files .Can you please provide some help with this.

**Comment by AkhilJ321** [comment]
@barshimi @yuval-hazaz .I added some changes according to the change request. Please review them, I could not understand the context part properly, so I missed that. It will be really helpful if you could give more insights if other changes are still needed.

**Comment by morhag90** [comment]
Hi @AkhilJ321, 
Thank you for your contributions :) 

You need to move the query to a file named: resourcesQueries.ts, then delete the new file you created named: useResources and use this query in the existing file under workspaces/hooks/useResources. In this file, you should expose the refetch and the data and use them in your component.

**Comment by AkhilJ321** [comment]
Hi @morhag90  ,I added the queries in the useResource hook file but when I am using this in generatesettingform component ,now I have to pass four arguments ,I am getting confused about what to pass in that , and there is already useQuery defined,so now if I am adding another query,refetch and data are getting clashed.

**Comment by AkhilJ321** [comment]
Hi @morhag90 ,I have added all the recommended changes now.Let me know if something more is required.

**Comment by AkhilJ321** [comment]
@yuval-hazaz I made the mentioned changes several days ago. It would be great if someone could review them.

**Pull request closed without merging**
