### PR TITLE
Updated discord link in prisma-db-readme

### PR DESCRIPTION
**Pull request by prasadfirame**
Bug Report :Change the Discord link in prisma-db -readme 

Close: #6241 

## PR Details
Updated the discord link in prisma-db -readme.md

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by souravjain540 — APPROVED** [review]

**Review by yuval-hazaz — APPROVED** [review]
Thanks for your first contribution to Amplication  💜🚀

**Comment by prasadfirame** [comment]
thank you for the opportunity ,Looking forward to make my next contribution..:)

**Comment by souravjain540** [comment]
@prasadfirame can I have your email for the swag? can you dm me that on discord?

**Comment by prasadfirame** [comment]
Sure ,@souravjain540 plz check your DM .

**Pull request merged**
