### PR TITLE
Add tests for Build Service

### PR DESCRIPTION
**Pull request by GalCegla**
Add following tests for Build service - calcBuildStatus:

-Add should return Invalid test
-Add should return build status Running , Failed and Completed tests

-Remaining todo: Add tests for  try/catch outcomes

[WIP]

### CODE REVIEW

**Comment by iddan** [comment]
Is this ready?

**Comment by GalCegla** [comment]
> Is this ready?

Not yet

**Comment by GalCegla** [comment]
@iddan Weird test called it.'should try to get build status, catch an error and return Failed'

**Comment by iddan** [comment]
Good job!

**Pull request merged**
