### PR TITLE
Improve Commits with No Message

### PR DESCRIPTION
**Pull request by asharonbaltazar**
Close: #4561 

## PR Details

Commits with no message displayed `"No Commit Message"` as a fallback, which isn't very helpful. This PR addresses this by improving the message with a commit ID. 

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by asharonbaltazar** [comment]
#### Question for the reviewers:

With the ID, commit messages have become extremely long and wrap the message in two lines. Perhaps it could be more. Are there any style changes you want addressed as well?

Screenshot 2022-12-07 at 7 15 17 PM

**Comment by GreenMachine01** [comment]
@asharonbaltazar We trim the id to show the last 8 characters on the commit page. let's be consistent and do the same for the commit message.

**Comment by asharonbaltazar** [comment]
#### Changes due to feedback:

Screenshot 2022-12-08 at 11 54 45 AM

**Review by yuval-hazaz — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
@asharonbaltazar, thanks for your first contribution to Amplication 🚀

**Pull request merged**
