### PR TITLE
fix: remove skeleton while building

### PR DESCRIPTION
**Pull request by b4s36t4**
Issue Number: #3711 

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by yuval-hazaz** [comment]
@b4s36t4 thanks for your contribution.
The issue is about the location of the skeleton on top of the text. so we need to keep it but just make sure it is positioned correctly. 

@alexbass86 can you please provide a link to Figma or a screenshot of how the skeleton should be positioned?

**Review by yuval-hazaz — CHANGES_REQUESTED** [review]
@b4s36t4 thanks for your contribution.
The issue is about the location of the skeleton on top of the text. so we need to keep it but just make sure it is positioned correctly.

@alexbass86 can you please provide a link to Figma or a screenshot of how the skeleton should be positioned?

**Comment by b4s36t4** [comment]
Oh sorry, will fix it. Will wait for the figma for position to change.

**Comment by b4s36t4** [comment]
@yuval-hazaz this change works?
Screenshot 2022-09-05 at 11 05 36 AM

**Comment by alexbass86** [comment]
> @b4s36t4 thanks for your contribution. The issue is about the location of the skeleton on top of the text. so we need to keep it but just make sure it is positioned correctly.
> 
> @alexbass86 can you please provide a link to Figma or a screenshot of how the skeleton should be positioned?

I think we can remove the skeleton loading on this section because we have a proper indication that it's in the process using the rotating loader on the right

image

**Comment by b4s36t4** [comment]
Then the PR would be fine to move on.

**Review by yuval-hazaz — APPROVED** [review]

**Pull request merged**
