### PR TITLE
[2401] - When role is applied to a field it jumps to the top of the list.

### PR DESCRIPTION
**Pull request by muhsinkamil**
Issue Number: https://github.com/amplication/amplication/issues/2401

## PR Details

- Fix the order of cache modification by finding the updated field and replacing it in the cache.

## PR Checklist
- [x] `npm test` doesn't throw any error

## Comments

- Please suggest if other better approaches are available. Would love to discuss other options ❤️

### CODE REVIEW

**Review by yuval-hazaz — APPROVED** [review]
looks good 🔥

**Comment by yuval-hazaz** [comment]
@mshidlov this PR is ready to be merged.

**Comment by muhsinkamil** [comment]
Hi @mshidlov Seems the PR is closed when you deleted the release branch :disappointed: 
cc: @yuval-hazaz

**Comment by yuval-hazaz** [comment]
@all-contributors please add @muhsinkamil for code

**Pull request merged**
