### PR TITLE
fix(client): main content padding right

### PR DESCRIPTION
**Pull request by abrl91**
Close: #6029 

### Summary
🖥️🖨️🎨

This pull request improves the appearance and usability of the page content and scrollbar elements in the client package. It adjusts the padding of the `page content` element and updates the scrollbar style in `mixin.scss` to match the design system.

> _`page content` padded_
> _scrollbar style harmonized_
> _winter web design_

### Walkthrough
* Remove right padding of page content element to align with sidebar and header ([link](https://github.com/amplication/amplication/pull/6165/files?diff=unified&w=0#diff-e6fa601f11c49c9c943c08a0cb5257e3312266477ab55e2c43ac7f2abbfda3daL9-R10))
* Restore right padding of page content element for print media query to prevent overflow ([link](https://github.com/amplication/amplication/pull/6165/files?diff=unified&w=0#diff-e6fa601f11c49c9c943c08a0cb5257e3312266477ab55e2c43ac7f2abbfda3daR34))
* Increase opacity of scrollbar thumb to improve visibility ([link](https://github.com/amplication/amplication/pull/6165/files?diff=unified&w=0#diff-32a6894d90022b03852964ffb2a469cfec9880bdb60788a78e9c09f693cba5e0L245-R245))
* Remove hover effect of scrollbar thumb to simplify style ([link](https://github.com/amplication/amplication/pull/6165/files?diff=unified&w=0#diff-32a6894d90022b03852964ffb2a469cfec9880bdb60788a78e9c09f693cba5e0L256-L261))

## PR Checklist

- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by abrl91** [comment]
@alexbass86 

https://github.com/amplication/amplication/assets/39680385/0444208b-01ed-4836-9e1d-2d0ec0f84d16

**Review by yuval-hazaz — COMMENTED** [review]
@abrl91 in the video, I don't see the scrollbar when it should be visible

Also, please have a look at this PR - https://github.com/amplication/amplication/commit/74cc977c0c27a19783f2e787e688a54d2cc922df

I see why removing the extra padding settings will revert the change - but:
1. what about the original issue the previous PR tries to fix? Is it resolved? Should we reopen? is it a matter of a specific browser? Specific page?
2. why did you decide to change the scrollbar settings? in the original PR they didn't change that, so I assume the previous state of the scrollbar worked correctly before the problem started with the previous PR

**Comment by abrl91** [comment]
> @abrl91 in the video, I don't see the scrollbar when it should be visible
> 
> Also, please have a look at this PR - [74cc977](https://github.com/amplication/amplication/commit/74cc977c0c27a19783f2e787e688a54d2cc922df)
> 
> I see why removing the extra padding settings will revert the change - but:
> 
> 1. what about the original issue the previous PR tries to fix? Is it resolved? Should we reopen? is it a matter of a specific browser? Specific page?
> 2. why did you decide to change the scrollbar settings? in the original PR they didn't change that, so I assume the previous state of the scrollbar worked correctly before the problem started with the previous PR

1. I don't see the original issue, now we have 16px , like in the design
2. when we open the console, the screen's height gets smaller and the scroller appears but its width was (another) 16px and then the padding-right was doubled, that's why I reduced the width. we can still sroll

**Comment by yuval-hazaz** [comment]
> * I don't see the original issue, now we have 16px , like in the design
> * when we open the console, the screen's height gets smaller and the scroller appears but its width was (another) 16px and then the padding-right was doubled, that's why I reduced the width. we can still sroll

1. I added a link to the original PR that caused the issue.
2. reducing the width of the scroll is not the right solution - unless we decide we want this behaviour across the board, and then we need to implement it in all pages (but I don't think we want to do that). 

we suppose to have 16px padding for the panel, and the scroll should not take extra space and should be positioned in the same space of the padding. If this is not the behavior, we should look for the reason why it is not that way - since it was working like this before. 
have a look at this page for example on how it should looks like 
image

**Review by yuval-hazaz — APPROVED** [review]

**Pull request merged**
