### PR TITLE
feat(client) - Side menu update

### PR DESCRIPTION
**Pull request by garvitrai013**
Issue Number: #2712 

## PR Details

1. Icons size changed from 32px to 24px
2. Unselected icon color changed to #A3A8B8
3. Hover/selected color changed to #515873

## PR Checklist
- ✅ Tested the changes
- ✅ `npm test` doesn't throw any error

### CODE REVIEW

**Comment by garvitrai013** [comment]
Are the changes correct according to the requirements?

**Comment by yuval-hazaz** [comment]
From a technical perspective, the change looks good to me.

@tupe12334 can you please deploy and let @alexbass86 approve the results so we can push this to 0.13.2?

**Comment by tupe12334** [comment]
@garvitrai013 I see that there is a problem with the service icon.
Look at the blue ```S``` in the side menu

Screen Shot 2022-06-20 at 18 53 31

**Comment by souravjain540** [comment]
@tupe12334 approve this PR please

**Comment by tupe12334** [comment]
@souravjain540 I'm not approving this pr because I gave @garvitrai013 a reject

**Comment by souravjain540** [comment]
> @souravjain540 I'm not approving this pr because I gave @garvitrai013 a reject

Oh sorry I will talk to him

**Comment by alexbass86** [comment]
run branch

**Comment by garvitrai013** [comment]
I can take it. I need to connect with a dev of yours once. There are a few things that I have doubts on

**Comment by yuval-hazaz** [comment]
@tupe12334 can you help @garvitrai013 complete this one?

**Comment by yuval-hazaz** [comment]
@garvitrai013, thanks for your support
we are working on a significant change in the UI, so we recently made a lot of changes in the client code
I believe it is better to close this PR for now to avoid conflicts, and we will take care of the menu update with the recent changes in mind


I am sorry it took us so long to reply on this one. 
Please feel free to ask @souravjain540 for a new issue to work on, and we will make sure you will be successfully in merging your PR this time

**Pull request closed without merging**
