### PR TITLE
added greeting GHA + added codeql GHA

### PR DESCRIPTION
**Pull request by Ayush7614**
This PR Contains

- Added Greeting Action for first issue and Pr Welcome
- Added Codeql GHA for Code Analysis

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @yuval-hazaz

**Comment by yuval-hazaz** [comment]
thanks @Ayush7614 

@mshidlov please see if and how we want to use codeQL
@MoFoGo  please review the greetings text

**Review by MoFoGo — APPROVED** [review]

**Comment by yuval-hazaz** [comment]
@mshidlov still waiting for your review

**Comment by Ayush7614** [comment]
cc @mshidlov

**Comment by yuval-hazaz** [comment]
@Ayush7614 thanks for the reminder.
@mshidlov was very busy lately with a big migration we are working on, we will review this soon and will keep you updated. 

thanks for your patience

**Comment by yuval-hazaz** [comment]
Hi @Ayush7614 sorry it took as so long to reply on this one. 
For focus purposes, we decided not to implement codeQL as you suggested in this PR 
we may be able to implement it or other tools in the future
thanks for you support

**Pull request closed without merging**
