### PR TITLE
fix: count type

### PR DESCRIPTION
**Pull request by Juicpt**
Issue Number: #2588 

## PR Details

Let count type be number

## PR Checklist
- [x] Tests for the changes have been added
- [x] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by yuval-hazaz — APPROVED** [review]
great catch! 
congrats on your first PR with us 🚀

**Comment by yuval-hazaz** [comment]
@tupe12334 please merge into the next release

**Comment by tupe12334** [comment]
@Juicpt Can you run the script ```update-test-data-service-snapshot``` in the  ```/packages/amplicaation-data-service-generator ```
This script updates the snapshot test
@yuval-hazaz I will merge it after @Juicpt will update the test

**Comment by Juicpt** [comment]
> @Juicpt Can you run the script `update-test-data-service-snapshot` in the `/packages/amplicaation-data-service-generator ` This script updates the snapshot test @yuval-hazaz I will merge it after @Juicpt will update the test

Sorry for my mistake. I have updated the Snapshot test

**Review by tupe12334 — APPROVED** [review]

**Comment by tupe12334** [comment]
Thanks @Juicpt, your pr has been merged and will be released in the next implication release (0.12.5)

**Comment by souravjain540** [comment]
Thank you @Juicpt ❤️

**Pull request merged**
