### PR TITLE
Propose some Grammatical changes in the README

### PR DESCRIPTION
**Pull request by omniscientHorizon**
Fixing Grammatical Errors on lines 75, 111,  129 and 135 to make the Readme easier to undertsand and read.

Issue Number: N/A

## PR Checklist
- [ ] Tests for the changes have been added
- [ ] `npm test` doesn't throw any error

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by MoFoGo — DISMISSED** [review]
Looks good.

**Comment by MoFoGo** [comment]
@souravjain540 - I have approved this. As @omniscientHorizon it's a first-time contributor, please take it from here.

**Review by yuval-hazaz — APPROVED** [review]

**Comment by souravjain540** [comment]
need your email @omniscientHorizon

**Comment by omniscientHorizon** [comment]
omniscienthorizon@gmail.com

**Pull request merged**
